//
// Bareflank Hypervisor
//
// Copyright (C) 2015 Assured Information Security, Inc.
// Author: Rian Quinn        <quinnr@ainfosec.com>
// Author: Brendan Kerrigan  <kerriganb@ainfosec.com>
//
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, write to the Free Software
// Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

#ifndef VMCS_INTEL_X64_FTOS_H
#define VMCS_INTEL_X64_FTOS_H

#include <intrinsics/intrinsics_intel_x64.h>

// *INDENT-OFF*

#ifndef STRINGIY_AND_RETURN
#define STRINGIY_AND_RETURN(a) \
    case a: return #a
#endif

static inline const char *
vmcs_field_to_str(uint64_t field)
{
    switch (field)
    {
        STRINGIY_AND_RETURN(VMCS_VIRTUAL_PROCESSOR_IDENTIFIER);
        STRINGIY_AND_RETURN(VMCS_POSTED_INTERRUPT_NOTIFICATION_VECTOR);
        STRINGIY_AND_RETURN(VMCS_EPTP_INDEX);
        STRINGIY_AND_RETURN(VMCS_GUEST_ES_SELECTOR);
        STRINGIY_AND_RETURN(VMCS_GUEST_CS_SELECTOR);
        STRINGIY_AND_RETURN(VMCS_GUEST_SS_SELECTOR);
        STRINGIY_AND_RETURN(VMCS_GUEST_DS_SELECTOR);
        STRINGIY_AND_RETURN(VMCS_GUEST_FS_SELECTOR);
        STRINGIY_AND_RETURN(VMCS_GUEST_GS_SELECTOR);
        STRINGIY_AND_RETURN(VMCS_GUEST_LDTR_SELECTOR);
        STRINGIY_AND_RETURN(VMCS_GUEST_TR_SELECTOR);
        STRINGIY_AND_RETURN(VMCS_GUEST_INTERRUPT_STATUS);
        STRINGIY_AND_RETURN(VMCS_HOST_ES_SELECTOR);
        STRINGIY_AND_RETURN(VMCS_HOST_CS_SELECTOR);
        STRINGIY_AND_RETURN(VMCS_HOST_SS_SELECTOR);
        STRINGIY_AND_RETURN(VMCS_HOST_DS_SELECTOR);
        STRINGIY_AND_RETURN(VMCS_HOST_FS_SELECTOR);
        STRINGIY_AND_RETURN(VMCS_HOST_GS_SELECTOR);
        STRINGIY_AND_RETURN(VMCS_HOST_TR_SELECTOR);
        STRINGIY_AND_RETURN(VMCS_ADDRESS_OF_IO_BITMAP_A_FULL);
        STRINGIY_AND_RETURN(VMCS_ADDRESS_OF_IO_BITMAP_A_HIGH);
        STRINGIY_AND_RETURN(VMCS_ADDRESS_OF_IO_BITMAP_B_FULL);
        STRINGIY_AND_RETURN(VMCS_ADDRESS_OF_IO_BITMAP_B_HIGH);
        STRINGIY_AND_RETURN(VMCS_ADDRESS_OF_MSR_BITMAPS_FULL);
        STRINGIY_AND_RETURN(VMCS_ADDRESS_OF_MSR_BITMAPS_HIGH);
        STRINGIY_AND_RETURN(VMCS_VM_EXIT_MSR_STORE_ADDRESS_FULL);
        STRINGIY_AND_RETURN(VMCS_VM_EXIT_MSR_STORE_ADDRESS_HIGH);
        STRINGIY_AND_RETURN(VMCS_VM_EXIT_MSR_LOAD_ADDRESS_FULL);
        STRINGIY_AND_RETURN(VMCS_VM_EXIT_MSR_LOAD_ADDRESS_HIGH);
        STRINGIY_AND_RETURN(VMCS_VM_ENTRY_MSR_LOAD_ADDRESS_FULL);
        STRINGIY_AND_RETURN(VMCS_VM_ENTRY_MSR_LOAD_ADDRESS_HIGH);
        STRINGIY_AND_RETURN(VMCS_EXECUTIVE_VMCS_POINTER_FULL);
        STRINGIY_AND_RETURN(VMCS_EXECUTIVE_VMCS_POINTER_HIGH);
        STRINGIY_AND_RETURN(VMCS_PML_ADDRESS_FULL);
        STRINGIY_AND_RETURN(VMCS_PML_ADDRESS_HIGH);
        STRINGIY_AND_RETURN(VMCS_TSC_OFFSET_FULL);
        STRINGIY_AND_RETURN(VMCS_TSC_OFFSET_HIGH);
        STRINGIY_AND_RETURN(VMCS_VIRTUAL_APIC_ADDRESS_FULL);
        STRINGIY_AND_RETURN(VMCS_VIRTUAL_APIC_ADDRESS_HIGH);
        STRINGIY_AND_RETURN(VMCS_APIC_ACCESS_ADDRESS_FULL);
        STRINGIY_AND_RETURN(VMCS_APIC_ACCESS_ADDRESS_HIGH);
        STRINGIY_AND_RETURN(VMCS_POSTED_INTERRUPT_DESCRIPTOR_ADDRESS_FULL);
        STRINGIY_AND_RETURN(VMCS_POSTED_INTERRUPT_DESCRIPTOR_ADDRESS_HIGH);
        STRINGIY_AND_RETURN(VMCS_VM_FUNCTION_CONTROLS_FULL);
        STRINGIY_AND_RETURN(VMCS_VM_FUNCTION_CONTROLS_HIGH);
        STRINGIY_AND_RETURN(VMCS_EPT_POINTER_FULL);
        STRINGIY_AND_RETURN(VMCS_EPT_POINTER_HIGH);
        STRINGIY_AND_RETURN(VMCS_EOI_EXIT_BITMAP_0_FULL);
        STRINGIY_AND_RETURN(VMCS_EOI_EXIT_BITMAP_0_HIGH);
        STRINGIY_AND_RETURN(VMCS_EOI_EXIT_BITMAP_1_FULL);
        STRINGIY_AND_RETURN(VMCS_EOI_EXIT_BITMAP_1_HIGH);
        STRINGIY_AND_RETURN(VMCS_EOI_EXIT_BITMAP_2_FULL);
        STRINGIY_AND_RETURN(VMCS_EOI_EXIT_BITMAP_2_HIGH);
        STRINGIY_AND_RETURN(VMCS_EOI_EXIT_BITMAP_3_FULL);
        STRINGIY_AND_RETURN(VMCS_EOI_EXIT_BITMAP_3_HIGH);
        STRINGIY_AND_RETURN(VMCS_EPTP_LIST_ADDRESS_FULL);
        STRINGIY_AND_RETURN(VMCS_EPTP_LIST_ADDRESS_HIGH);
        STRINGIY_AND_RETURN(VMCS_VMREAD_BITMAP_ADDRESS_FULL);
        STRINGIY_AND_RETURN(VMCS_VMREAD_BITMAP_ADDRESS_HIGH);
        STRINGIY_AND_RETURN(VMCS_VMWRITE_BITMAP_ADDRESS_FULL);
        STRINGIY_AND_RETURN(VMCS_VMWRITE_BITMAP_ADDRESS_HIGH);
        STRINGIY_AND_RETURN(VMCS_VIRTUALIZATION_EXCEPTION_INFORMATION_ADDRESS_FULL);
        STRINGIY_AND_RETURN(VMCS_VIRTUALIZATION_EXCEPTION_INFORMATION_ADDRESS_HIGH);
        STRINGIY_AND_RETURN(VMCS_XSS_EXITING_BITMAP_FULL);
        STRINGIY_AND_RETURN(VMCS_XSS_EXITING_BITMAP_HIGH);
        STRINGIY_AND_RETURN(VMCS_GUEST_PHYSICAL_ADDRESS_FULL);
        STRINGIY_AND_RETURN(VMCS_GUEST_PHYSICAL_ADDRESS_HIGH);
        STRINGIY_AND_RETURN(VMCS_VMCS_LINK_POINTER_FULL);
        STRINGIY_AND_RETURN(VMCS_VMCS_LINK_POINTER_HIGH);
        STRINGIY_AND_RETURN(VMCS_GUEST_IA32_DEBUGCTL_FULL);
        STRINGIY_AND_RETURN(VMCS_GUEST_IA32_DEBUGCTL_HIGH);
        STRINGIY_AND_RETURN(VMCS_GUEST_IA32_PAT_FULL);
        STRINGIY_AND_RETURN(VMCS_GUEST_IA32_PAT_HIGH);
        STRINGIY_AND_RETURN(VMCS_GUEST_IA32_EFER_FULL);
        STRINGIY_AND_RETURN(VMCS_GUEST_IA32_EFER_HIGH);
        STRINGIY_AND_RETURN(VMCS_GUEST_IA32_PERF_GLOBAL_CTRL_FULL);
        STRINGIY_AND_RETURN(VMCS_GUEST_IA32_PERF_GLOBAL_CTRL_HIGH);
        STRINGIY_AND_RETURN(VMCS_GUEST_PDPTE0_FULL);
        STRINGIY_AND_RETURN(VMCS_GUEST_PDPTE0_HIGH);
        STRINGIY_AND_RETURN(VMCS_GUEST_PDPTE1_FULL);
        STRINGIY_AND_RETURN(VMCS_GUEST_PDPTE1_HIGH);
        STRINGIY_AND_RETURN(VMCS_GUEST_PDPTE2_FULL);
        STRINGIY_AND_RETURN(VMCS_GUEST_PDPTE2_HIGH);
        STRINGIY_AND_RETURN(VMCS_GUEST_PDPTE3_FULL);
        STRINGIY_AND_RETURN(VMCS_GUEST_PDPTE3_HIGH);
        STRINGIY_AND_RETURN(VMCS_HOST_IA32_PAT_FULL);
        STRINGIY_AND_RETURN(VMCS_HOST_IA32_PAT_HIGH);
        STRINGIY_AND_RETURN(VMCS_HOST_IA32_EFER_FULL);
        STRINGIY_AND_RETURN(VMCS_HOST_IA32_EFER_HIGH);
        STRINGIY_AND_RETURN(VMCS_HOST_IA32_PERF_GLOBAL_CTRL_FULL);
        STRINGIY_AND_RETURN(VMCS_HOST_IA32_PERF_GLOBAL_CTRL_HIGH);
        STRINGIY_AND_RETURN(VMCS_PIN_BASED_VM_EXECUTION_CONTROLS);
        STRINGIY_AND_RETURN(VMCS_PRIMARY_PROCESSOR_BASED_VM_EXECUTION_CONTROLS);
        STRINGIY_AND_RETURN(VMCS_EXCEPTION_BITMAP);
        STRINGIY_AND_RETURN(VMCS_PAGE_FAULT_ERROR_CODE_MASK);
        STRINGIY_AND_RETURN(VMCS_PAGE_FAULT_ERROR_CODE_MATCH);
        STRINGIY_AND_RETURN(VMCS_CR3_TARGET_COUNT);
        STRINGIY_AND_RETURN(VMCS_VM_EXIT_CONTROLS);
        STRINGIY_AND_RETURN(VMCS_VM_EXIT_MSR_STORE_COUNT);
        STRINGIY_AND_RETURN(VMCS_VM_EXIT_MSR_LOAD_COUNT);
        STRINGIY_AND_RETURN(VMCS_VM_ENTRY_CONTROLS);
        STRINGIY_AND_RETURN(VMCS_VM_ENTRY_MSR_LOAD_COUNT);
        STRINGIY_AND_RETURN(VMCS_VM_ENTRY_INTERRUPTION_INFORMATION_FIELD);
        STRINGIY_AND_RETURN(VMCS_VM_ENTRY_EXCEPTION_ERROR_CODE);
        STRINGIY_AND_RETURN(VMCS_VM_ENTRY_INSTRUCTION_LENGTH);
        STRINGIY_AND_RETURN(VMCS_TPR_THRESHOLD);
        STRINGIY_AND_RETURN(VMCS_SECONDARY_PROCESSOR_BASED_VM_EXECUTION_CONTROLS);
        STRINGIY_AND_RETURN(VMCS_PLE_GAP);
        STRINGIY_AND_RETURN(VMCS_PLE_WINDOW);
        STRINGIY_AND_RETURN(VMCS_VM_INSTRUCTION_ERROR);
        STRINGIY_AND_RETURN(VMCS_EXIT_REASON);
        STRINGIY_AND_RETURN(VMCS_VM_EXIT_INTERRUPTION_INFORMATION);
        STRINGIY_AND_RETURN(VMCS_VM_EXIT_INTERRUPTION_ERROR_CODE);
        STRINGIY_AND_RETURN(VMCS_IDT_VECTORING_INFORMATION_FIELD);
        STRINGIY_AND_RETURN(VMCS_IDT_VECTORING_ERROR_CODE);
        STRINGIY_AND_RETURN(VMCS_VM_EXIT_INSTRUCTION_LENGTH);
        STRINGIY_AND_RETURN(VMCS_VM_EXIT_INSTRUCTION_INFORMATION);
        STRINGIY_AND_RETURN(VMCS_GUEST_ES_LIMIT);
        STRINGIY_AND_RETURN(VMCS_GUEST_CS_LIMIT);
        STRINGIY_AND_RETURN(VMCS_GUEST_SS_LIMIT);
        STRINGIY_AND_RETURN(VMCS_GUEST_DS_LIMIT);
        STRINGIY_AND_RETURN(VMCS_GUEST_FS_LIMIT);
        STRINGIY_AND_RETURN(VMCS_GUEST_GS_LIMIT);
        STRINGIY_AND_RETURN(VMCS_GUEST_LDTR_LIMIT);
        STRINGIY_AND_RETURN(VMCS_GUEST_TR_LIMIT);
        STRINGIY_AND_RETURN(VMCS_GUEST_GDTR_LIMIT);
        STRINGIY_AND_RETURN(VMCS_GUEST_IDTR_LIMIT);
        STRINGIY_AND_RETURN(VMCS_GUEST_ES_ACCESS_RIGHTS);
        STRINGIY_AND_RETURN(VMCS_GUEST_CS_ACCESS_RIGHTS);
        STRINGIY_AND_RETURN(VMCS_GUEST_SS_ACCESS_RIGHTS);
        STRINGIY_AND_RETURN(VMCS_GUEST_DS_ACCESS_RIGHTS);
        STRINGIY_AND_RETURN(VMCS_GUEST_FS_ACCESS_RIGHTS);
        STRINGIY_AND_RETURN(VMCS_GUEST_GS_ACCESS_RIGHTS);
        STRINGIY_AND_RETURN(VMCS_GUEST_LDTR_ACCESS_RIGHTS);
        STRINGIY_AND_RETURN(VMCS_GUEST_TR_ACCESS_RIGHTS);
        STRINGIY_AND_RETURN(VMCS_GUEST_INTERRUPTIBILITY_STATE);
        STRINGIY_AND_RETURN(VMCS_GUEST_ACTIVITY_STATE);
        STRINGIY_AND_RETURN(VMCS_GUEST_SMBASE);
        STRINGIY_AND_RETURN(VMCS_GUEST_IA32_SYSENTER_CS);
        STRINGIY_AND_RETURN(VMCS_VMX_PREEMPTION_TIMER_VALUE);
        STRINGIY_AND_RETURN(VMCS_HOST_IA32_SYSENTER_CS);
        STRINGIY_AND_RETURN(VMCS_CR0_GUEST_HOST_MASK);
        STRINGIY_AND_RETURN(VMCS_CR4_GUEST_HOST_MASK);
        STRINGIY_AND_RETURN(VMCS_CR0_READ_SHADOW);
        STRINGIY_AND_RETURN(VMCS_CR4_READ_SHADOW);
        STRINGIY_AND_RETURN(VMCS_CR3_TARGET_VALUE_0);
        STRINGIY_AND_RETURN(VMCS_CR3_TARGET_VALUE_1);
        STRINGIY_AND_RETURN(VMCS_CR3_TARGET_VALUE_2);
        STRINGIY_AND_RETURN(VMCS_CR3_TARGET_VALUE_31);
        STRINGIY_AND_RETURN(VMCS_EXIT_QUALIFICATION);
        STRINGIY_AND_RETURN(VMCS_IO_RCX);
        STRINGIY_AND_RETURN(VMCS_IO_RSI);
        STRINGIY_AND_RETURN(VMCS_IO_RDI);
        STRINGIY_AND_RETURN(VMCS_IO_RIP);
        STRINGIY_AND_RETURN(VMCS_GUEST_LINEAR_ADDRESS);
        STRINGIY_AND_RETURN(VMCS_GUEST_CR0);
        STRINGIY_AND_RETURN(VMCS_GUEST_CR3);
        STRINGIY_AND_RETURN(VMCS_GUEST_CR4);
        STRINGIY_AND_RETURN(VMCS_GUEST_ES_BASE);
        STRINGIY_AND_RETURN(VMCS_GUEST_CS_BASE);
        STRINGIY_AND_RETURN(VMCS_GUEST_SS_BASE);
        STRINGIY_AND_RETURN(VMCS_GUEST_DS_BASE);
        STRINGIY_AND_RETURN(VMCS_GUEST_FS_BASE);
        STRINGIY_AND_RETURN(VMCS_GUEST_GS_BASE);
        STRINGIY_AND_RETURN(VMCS_GUEST_LDTR_BASE);
        STRINGIY_AND_RETURN(VMCS_GUEST_TR_BASE);
        STRINGIY_AND_RETURN(VMCS_GUEST_GDTR_BASE);
        STRINGIY_AND_RETURN(VMCS_GUEST_IDTR_BASE);
        STRINGIY_AND_RETURN(VMCS_GUEST_DR7);
        STRINGIY_AND_RETURN(VMCS_GUEST_RSP);
        STRINGIY_AND_RETURN(VMCS_GUEST_RIP);
        STRINGIY_AND_RETURN(VMCS_GUEST_RFLAGS);
        STRINGIY_AND_RETURN(VMCS_GUEST_PENDING_DEBUG_EXCEPTIONS);
        STRINGIY_AND_RETURN(VMCS_GUEST_IA32_SYSENTER_ESP);
        STRINGIY_AND_RETURN(VMCS_GUEST_IA32_SYSENTER_EIP);
        STRINGIY_AND_RETURN(VMCS_HOST_CR0);
        STRINGIY_AND_RETURN(VMCS_HOST_CR3);
        STRINGIY_AND_RETURN(VMCS_HOST_CR4);
        STRINGIY_AND_RETURN(VMCS_HOST_FS_BASE);
        STRINGIY_AND_RETURN(VMCS_HOST_GS_BASE);
        STRINGIY_AND_RETURN(VMCS_HOST_TR_BASE);
        STRINGIY_AND_RETURN(VMCS_HOST_GDTR_BASE);
        STRINGIY_AND_RETURN(VMCS_HOST_IDTR_BASE);
        STRINGIY_AND_RETURN(VMCS_HOST_IA32_SYSENTER_ESP);
        STRINGIY_AND_RETURN(VMCS_HOST_IA32_SYSENTER_EIP);
        STRINGIY_AND_RETURN(VMCS_HOST_RSP);
        STRINGIY_AND_RETURN(VMCS_HOST_RIP);
    }

    return "UNDEFINED_VMCS_FIELD";
}

// *INDENT-ON*

#endif
