#
# Copyright (C) 2019 Assured Information Security, Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

codecov:
  notify:
    require_ci_to_pass: no

coverage:
  status:
    project: yes
    patch: no
    changes: no
  precision: 2
  round: down
  range: "100...100"

parsers:
  gcov:
    branch_detection:
      conditional: no
      loop: no
      method: no
      macro: no

ignore:
  - "bfintrinsics/**"
  - "bfm/ioctl/arch/**"
  - "bfvmm/include/test/**"
  - "bfdriver/**"

  # Remove Me
  - "bfelf_loader/**"
  - "bfvmm/include/hve/arch/intel_x64/ept/mmap.h"
  - "bfvmm/include/hve/arch/intel_x64/vcpu.h"
  - "bfvmm/include/hve/arch/x64/unmapper.h"
  - "bfvmm/src/hve/arch/intel_x64/ept.cpp"
  - "bfvmm/src/hve/arch/intel_x64/interrupt_queue.cpp"
  - "bfvmm/src/hve/arch/intel_x64/microcode.cpp"
  - "bfvmm/src/hve/arch/intel_x64/mtrrs.cpp"
  - "bfvmm/src/hve/arch/intel_x64/vcpu.cpp"
  - "bfvmm/src/hve/arch/intel_x64/vmexit/**"
  - "bfvmm/src/hve/arch/intel_x64/vpid.cpp"
  - "bfvmm/src/hve/arch/x64/unmapper.cpp"
  # Remove Me

comment:
  layout: "header, diff, files"
  behavior: default
  require_changes: no
