export BUILD_ABS="/home/user/hypervisor"
export HYPER_ABS="/home/user/hypervisor"
export LLVM_RELEASE="release_39"
export module_file="/home/user/hypervisor/bfm/bin/native/vmm.modules"
export linker="ld"
export compiler="clang"
export CFLAGS=" -fpic -fexceptions -mmmx -msse -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -msse4 -mavx -mno-red-zone -mstackrealign -fstack-protector-strong -std=c99"
export CXXFLAGS=" -fpic -fexceptions -mmmx -msse -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -msse4 -mavx -mno-red-zone -mstackrealign -fstack-protector-strong -std=c++14"
export extensions=";"
