#!/bin/bash -e

# ------------------------------------------------------------------------------
# Mode
# ------------------------------------------------------------------------------

MODE="link"
TYPE="binary"

for ARG in "$@"
do
    if [[ $ARG == "-c" ]]; then
        MODE="compile"
    fi

    if [[ $ARG == "-shared" ]]; then
        TYPE="shared"
    fi
done

# ------------------------------------------------------------------------------
# Compiler
# ------------------------------------------------------------------------------

COMPILER="unsupported"

if [[ $0 == *"gcc" ]]; then
    COMPILER="$HOME/opt/cross/bin/x86_64-elf-gcc"
fi

if [[ $0 == *"g++" ]]; then
    COMPILER="$HOME/opt/cross/bin/x86_64-elf-g++"
fi

if [[ $COMPILER == "unsupported" ]]; then
    echo "You cannot use the wrapper directly. Instead, use a symlink that ends in gcc or g++"
    exit 1
fi

# ------------------------------------------------------------------------------
# Unsupported
# ------------------------------------------------------------------------------

UNSUPPORTED=false

for ARG in "$@"
do
    if [[ $MODE == "link" ]]; then
        if [[ $ARG == *".c" ]]; then
            UNSUPPORTED=true
        fi
        if [[ $ARG == *".cpp" ]]; then
            UNSUPPORTED=true
        fi
    fi
done

if [[ $UNSUPPORTED == "true" ]]; then
    echo "Compiling and linking at the same time is not supported. Use -c"
    exit 1
fi

# ------------------------------------------------------------------------------
# Convert Arguments
# ------------------------------------------------------------------------------

i=0
CONVERTED_ARGS[$i]=

for ARG in "$@"
do

    if [[ $MODE == "link" ]]; then

        # We need to convert the GCC syntax for passing LD flags to LD so that
        # LD is getting the correct settings.
        if [[ $ARG == "-Wl,"* ]]; then
            ARG=${ARG/-Wl,/}
            ARG=${ARG/,/ }
        fi

        # GCC's syntax is different than LD's for this option.
        if [[ $ARG == "-rdynamic" ]]; then
            ARG="-export-dynamic"
        fi

    fi

    CONVERTED_ARGS[$i]=$ARG
    i=$((i + 1))

done

# ------------------------------------------------------------------------------
# Filter Arguments
# ------------------------------------------------------------------------------

i=0
ARGS[$i]=

for ARG in "${CONVERTED_ARGS[@]}"
do

    if [[ $MODE == "link" ]]; then

        # These flags are all specific to GCC and are not used by LD. CMake
        # will send these to GCC, and GCC filters them similar to what we
        # do here.
        if [[ $ARG == "-m"* ]]; then continue; fi
        if [[ $ARG == "-f"* ]]; then continue; fi
        if [[ $ARG == "-W"* ]]; then continue; fi
        if [[ $ARG == "-D"* ]]; then continue; fi
        if [[ $ARG == "-U"* ]]; then continue; fi

        # For some reason, Libc++abi turns this on for a shared library, and
        # we really don't want it as we provide the symbols as needed. In
        # general if this is enabled, we should disable it.
        if [[ $ARG == "-z defs" ]]; then
            echo "WARNING: -z defs disabled by bareflank-gcc-wrapper"
            continue;
        fi

        # These are not used by LD, and actually cause LD to do some pretty
        # terrible things. For example, nodefaults tells LD to use "-n" which
        # changes the permissions from RE/RW -> RWE which is really bad.
        if [[ $ARG == "-std"* ]]; then continue; fi
        if [[ $ARG == "-nodefaultlibs" ]]; then continue; fi

    fi

    ARGS[$i]=$ARG
    i=$((i + 1))

done

# ------------------------------------------------------------------------------
# Sysroot Libraries
# ------------------------------------------------------------------------------

# By default, bareflank does not support the use of libc or libc++ as static
# libraries. Instead, libc is only used to create libc++, and libc++ must
# be loaded at runtime, and thus does not need to be known during linking. The
# only thing the hypervisor code should need from the sysroot is the includes.

if [[ $BAREFLANK_WRAPPER_IS_LIBCXX == "true" ]]; then
    SYSROOT_LIBS+="-lc -lbfc -lbfunwind_static "
    SYSROOT_LIBS+="-u __cxa_throw_bad_array_new_length"
fi

SYSROOT_LIB_PATH="-L$HOME/opt/cross/x86_64-elf/lib/"

# ------------------------------------------------------------------------------
# Sysroot Includes
# ------------------------------------------------------------------------------

SYSROOT_INC_PATH="-I$HOME/opt/cross/x86_64-elf/include/ -I$HOME/opt/cross/x86_64-elf/include/c++/v1/ "

# ------------------------------------------------------------------------------
# Libgcc
# ------------------------------------------------------------------------------

if [[ $BAREFLANK_WRAPPER_IGNORE_CRT != "true" ]]; then
    if [[ $MODE == "link" ]] && [[ $TYPE == "shared" ]]; then
        BAREFLANK_LIBS="-u local_init -u local_fini -lbfcrt_static "
    fi
fi

# ------------------------------------------------------------------------------
# Execute
# ------------------------------------------------------------------------------

if [ ! -z "$VERBOSE" ]; then
    echo "ARGS: $@"
    echo "MODE: $MODE"
    echo "COMPILER: $COMPILER"
    echo "FILTERED ARGS: ${ARGS[*]}"
    echo "SYSROOT_LIBS: $SYSROOT_LIBS"
    echo "SYSROOT_LIB_PATH: $SYSROOT_LIB_PATH"
    echo "SYSROOT_INC_PATH: $SYSROOT_INC_PATH"
    echo "BAREFLANK_LIBS: $BAREFLANK_LIBS"
    echo ""
fi

if [[ $MODE == "compile" ]]; then
    $COMPILER $SYSROOT_INC_PATH ${ARGS[*]}
fi

if [[ $MODE == "link" ]]; then
    $HOME/opt/cross/bin/x86_64-elf-ld ${ARGS[*]} $SYSROOT_LIB_PATH $SYSROOT_LIBS $BAREFLANK_LIBS -z max-page-size=4096 -z relro -z now
fi
