function(print_usage)
    message(STATUS "")
    if(UNIX)
        message(STATUS "${Green} For more build options:${ColorReset}")
        message(STATUS "${Yellow}    ${BAREFLANK_BUILD_COMMAND} info${ColorReset}")
    else()
        message(STATUS "${Green} Additional build options include:${ColorReset}")
        message(STATUS "${Yellow}    cmake --build . --target unittest${ColorReset}")
        message(STATUS "${Yellow}    cmake --build . --target clean-all${ColorReset}")
    endif()
    message(STATUS "")
endfunction(print_usage)
