#ifndef MICROV_VMEXIT_CONTEXT_HPP
#define MICROV_VMEXIT_CONTEXT_HPP

class pal_context
{
    // TODO: This will probably be generated by the PAL project eventually
};

class vmexit_context : public pal_context
{
    // TODO: This will probably be defined by the kernel component eventually
};

#endif
