var searchData=
[
  ['idt_5ft',['idt_t',['../structidt__t.html',1,'']]],
  ['intrinsics_5fintel_5fx64',['intrinsics_intel_x64',['../classintrinsics__intel__x64.html',1,'']]],
  ['intrinsics_5fx64',['intrinsics_x64',['../classintrinsics__x64.html',1,'']]],
  ['invalid_5faddress_5ferror',['invalid_address_error',['../classbfn_1_1invalid__address__error.html',1,'bfn']]],
  ['invalid_5falignment_5ferror',['invalid_alignment_error',['../classbfn_1_1invalid__alignment__error.html',1,'bfn']]],
  ['invalid_5fdebug_5fring_5ferror',['invalid_debug_ring_error',['../classbfn_1_1invalid__debug__ring__error.html',1,'bfn']]],
  ['invalid_5ffile_5ferror',['invalid_file_error',['../classbfn_1_1invalid__file__error.html',1,'bfn']]],
  ['invalid_5fmdl_5ferror',['invalid_mdl_error',['../classbfn_1_1invalid__mdl__error.html',1,'bfn']]],
  ['invalid_5fvmcs_5ferror',['invalid_vmcs_error',['../classbfn_1_1invalid__vmcs__error.html',1,'bfn']]],
  ['invalid_5fvmm_5fstate_5ferror',['invalid_vmm_state_error',['../classbfn_1_1invalid__vmm__state__error.html',1,'bfn']]],
  ['invalid_5fvmxon_5ferror',['invalid_vmxon_error',['../classbfn_1_1invalid__vmxon__error.html',1,'bfn']]],
  ['ioctl',['ioctl',['../classioctl.html',1,'']]],
  ['ioctl_5fdriver',['ioctl_driver',['../classioctl__driver.html',1,'']]],
  ['ioctl_5ffailed_5ferror',['ioctl_failed_error',['../classbfn_1_1ioctl__failed__error.html',1,'bfn']]],
  ['ioctl_5fprivate',['ioctl_private',['../classioctl__private.html',1,'']]],
  ['ioctl_5fprivate_5fbase',['ioctl_private_base',['../classioctl__private__base.html',1,'']]]
];
