//
// Bareflank Hypervisor
//
// Copyright (C) 2015 Assured Information Security, Inc.
// Author: Rian Quinn        <quinnr@ainfosec.com>
// Author: Brendan Kerrigan  <kerriganb@ainfosec.com>
//
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, write to the Free Software
// Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

#ifndef TEST_H
#define TEST_H

#include <unittest.h>
#include <vector>
#include <functional>
#include <memory>
#include <vmcs/vmcs_intel_x64.h>
#include <vmcs/vmcs_intel_x64_32bit_control_fields.h>
#include <vmcs/vmcs_intel_x64_32bit_read_only_data_fields.h>
#include <memory_manager/memory_manager_x64.h>

#include <intrinsics/msrs_intel_x64.h>

#define test_vmcs_check(cfg, ...) test_vmcs_check_with_args(gsl::cstring_span<>(__PRETTY_FUNCTION__), __LINE__, cfg, __VA_ARGS__)

using namespace intel_x64;

struct control_flow_path
{
    std::function<void()> setup;
    std::shared_ptr<std::exception> exception;
    bool throws_exception;
};

struct vm_control;

struct cpuid_regs
{
    uint32_t eax;
    uint32_t ebx;
    uint32_t ecx;
    uint32_t edx;
};


extern std::map<uint32_t, uint64_t> g_msrs;
extern std::map<uint64_t, uint64_t> g_vmcs_fields;
extern std::map<uint32_t, uint32_t> g_eax_cpuid;
extern bool g_virt_to_phys_return_nullptr;
extern bool g_phys_to_virt_return_nullptr;
extern uintptr_t g_test_addr;
extern uintptr_t g_virt_apic_addr;
extern uintptr_t g_vmcs_link_addr;
extern uintptr_t g_pdpt_addr;
extern struct cpuid_regs g_cpuid_regs;

extern uint8_t g_virt_apic_mem[0x81];
extern uint32_t g_vmcs_link_mem[1];
extern uint64_t g_pdpt_mem[4];

void setup_mock(MockRepository &mocks, memory_manager_x64 *mm);
uintptr_t virtptr_to_physint(void *ptr);
void *physint_to_virtptr(uintptr_t phys);

void proc_ctl_allow1(uint64_t mask);
void proc_ctl_allow0(uint64_t mask);
void proc_ctl_disallow1(uint64_t mask);

void proc_ctl2_allow1(uint64_t mask);
void proc_ctl2_allow0(uint64_t mask);
void proc_ctl2_disallow1(uint64_t mask);

void pin_ctl_allow1(uint64_t mask);
void pin_ctl_allow0(uint64_t mask);

void exit_ctl_allow1(uint64_t mask);
void exit_ctl_allow0(uint64_t mask);

void entry_ctl_allow1(uint64_t mask);
void entry_ctl_allow0(uint64_t mask);

void vmfunc_ctl_allow1(uint64_t mask);

class vmcs_ut : public unittest
{
public:

    vmcs_ut();
    ~vmcs_ut() override = default;

protected:

    bool init() override;
    bool fini() override;
    bool list() override;

    template<class L, class C,
             class = typename std::enable_if<std::is_integral<L>::value>::type>
    void test_vmcs_check_with_args(gsl::cstring_span<> fut, L line,
                                   const std::vector<struct control_flow_path> &cfg, C chk)
    {
        for (int i = 0; static_cast<size_t>(i) < cfg.size(); i++)
        {
            MockRepository mocks;
            auto mm = mocks.Mock<memory_manager_x64>();

            setup_mock(mocks, mm);

            auto path = cfg[static_cast<size_t>(i)];
            path.setup();

            RUN_UNITTEST_WITH_MOCKS(mocks, [&]
            {
                if (path.throws_exception)
                    this->expect_exception_with_args(std::forward<decltype(chk)>(chk), path.exception, fut, line, i);
                else
                    this->expect_no_exception_with_args(std::forward<decltype(chk)>(chk), fut, line, i);
            });
        }
    }

private:

    void list_vmcs_intel_x64_cpp();
    void list_vmcs_intel_x64_h();
    void list_16bit_control_fields();
    void list_16bit_guest_state_fields();
    void list_16bit_host_state_fields();
    void list_64bit_control_fields();
    void list_64bit_read_only_data_field();
    void list_64bit_guest_state_fields();
    void list_64bit_host_state_fields();
    void list_32bit_control_fields();
    void list_32bit_read_only_data_fields();
    void list_32bit_guest_state_fields();
    void list_32bit_host_state_field();
    void list_natural_width_control_fields();
    void list_natural_width_read_only_data_fields();
    void list_natural_width_guest_state_fields();
    void list_natural_width_host_state_fields();

    void list_checks_on_vmx_controls();
    void list_checks_on_host_state();
    void list_checks_on_guest_state();

    void test_launch_success();
    void test_launch_vmlaunch_failure();
    void test_launch_vmlaunch_demote_failure();
    void test_launch_create_vmcs_region_failure();
    void test_launch_create_exit_handler_stack_failure();
    void test_launch_clear_failure();
    void test_launch_load_failure();
    void test_promote_failure();
    void test_resume_failure();
    void test_get_vmcs_field();
    void test_get_vmcs_field_if_exists();
    void test_set_vmcs_field();
    void test_set_vmcs_field_if_exists();
    void test_set_vm_control();
    void test_set_vm_control_if_allowed();
    void test_set_vm_function_control();
    void test_set_vm_function_control_if_allowed();
    void test_vmcs_vm_instruction_error_description();
    void test_vmcs_vm_instruction_error_description_if_exists();
    void test_vmcs_virtual_processor_identifier();
    void test_vmcs_posted_interrupt_notification_vector();
    void test_vmcs_eptp_index();
    void test_vmcs_guest_es_selector();
    void test_vmcs_guest_es_selector_rpl();
    void test_vmcs_guest_es_selector_ti();
    void test_vmcs_guest_es_selector_index();
    void test_vmcs_guest_cs_selector();
    void test_vmcs_guest_cs_selector_rpl();
    void test_vmcs_guest_cs_selector_ti();
    void test_vmcs_guest_cs_selector_index();
    void test_vmcs_guest_ss_selector();
    void test_vmcs_guest_ss_selector_rpl();
    void test_vmcs_guest_ss_selector_ti();
    void test_vmcs_guest_ss_selector_index();
    void test_vmcs_guest_ds_selector();
    void test_vmcs_guest_ds_selector_rpl();
    void test_vmcs_guest_ds_selector_ti();
    void test_vmcs_guest_ds_selector_index();
    void test_vmcs_guest_fs_selector();
    void test_vmcs_guest_fs_selector_rpl();
    void test_vmcs_guest_fs_selector_ti();
    void test_vmcs_guest_fs_selector_index();
    void test_vmcs_guest_gs_selector();
    void test_vmcs_guest_gs_selector_rpl();
    void test_vmcs_guest_gs_selector_ti();
    void test_vmcs_guest_gs_selector_index();
    void test_vmcs_guest_ldtr_selector();
    void test_vmcs_guest_ldtr_selector_rpl();
    void test_vmcs_guest_ldtr_selector_ti();
    void test_vmcs_guest_ldtr_selector_index();
    void test_vmcs_guest_tr_selector();
    void test_vmcs_guest_tr_selector_rpl();
    void test_vmcs_guest_tr_selector_ti();
    void test_vmcs_guest_tr_selector_index();
    void test_vmcs_guest_interrupt_status();
    void test_vmcs_host_es_selector();
    void test_vmcs_host_es_selector_rpl();
    void test_vmcs_host_es_selector_ti();
    void test_vmcs_host_es_selector_index();
    void test_vmcs_host_cs_selector();
    void test_vmcs_host_cs_selector_rpl();
    void test_vmcs_host_cs_selector_ti();
    void test_vmcs_host_cs_selector_index();
    void test_vmcs_host_ss_selector();
    void test_vmcs_host_ss_selector_rpl();
    void test_vmcs_host_ss_selector_ti();
    void test_vmcs_host_ss_selector_index();
    void test_vmcs_host_ds_selector();
    void test_vmcs_host_ds_selector_rpl();
    void test_vmcs_host_ds_selector_ti();
    void test_vmcs_host_ds_selector_index();
    void test_vmcs_host_fs_selector();
    void test_vmcs_host_fs_selector_rpl();
    void test_vmcs_host_fs_selector_ti();
    void test_vmcs_host_fs_selector_index();
    void test_vmcs_host_gs_selector();
    void test_vmcs_host_gs_selector_rpl();
    void test_vmcs_host_gs_selector_ti();
    void test_vmcs_host_gs_selector_index();
    void test_vmcs_host_tr_selector();
    void test_vmcs_host_tr_selector_rpl();
    void test_vmcs_host_tr_selector_ti();
    void test_vmcs_host_tr_selector_index();
    void test_vmcs_address_of_io_bitmap_a();
    void test_vmcs_address_of_io_bitmap_b();
    void test_vmcs_address_of_msr_bitmap();
    void test_vmcs_vm_exit_msr_store_address();
    void test_vmcs_vm_exit_msr_load_address();
    void test_vmcs_vm_entry_msr_load_address();
    void test_vmcs_executive_vmcs_pointer();
    void test_vmcs_pml_address();
    void test_vmcs_tsc_offset();
    void test_vmcs_virtual_apic_address();
    void test_vmcs_apic_access_address();
    void test_vmcs_posted_interrupt_descriptor_address();
    void test_vmcs_vm_function_controls();
    void test_vmcs_vm_function_controls_eptp_switching();
    void test_vmcs_vm_function_controls_reserved();
    void test_vmcs_ept_pointer();
    void test_vmcs_ept_pointer_memory_type();
    void test_vmcs_ept_pointer_page_walk_length_minus_one();
    void test_vmcs_ept_pointer_accessed_and_dirty_flags();
    void test_vmcs_ept_pointer_phys_addr();
    void test_vmcs_ept_pointer_reserved();
    void test_vmcs_eoi_exit_bitmap_0();
    void test_vmcs_eoi_exit_bitmap_1();
    void test_vmcs_eoi_exit_bitmap_2();
    void test_vmcs_eoi_exit_bitmap_3();
    void test_vmcs_eptp_list_address();
    void test_vmcs_vmread_bitmap_address();
    void test_vmcs_vmwrite_bitmap_address();
    void test_vmcs_virtualization_exception_information_address();
    void test_vmcs_xss_exiting_bitmap();
    void test_vmcs_guest_physical_address();
    void test_vmcs_guest_rflags();
    void test_vmcs_guest_rflags_carry_flag();
    void test_vmcs_guest_rflags_parity_flag();
    void test_vmcs_guest_rflags_auxiliary_carry_flag();
    void test_vmcs_guest_rflags_zero_flag();
    void test_vmcs_guest_rflags_sign_flag();
    void test_vmcs_guest_rflags_trap_flag();
    void test_vmcs_guest_rflags_interrupt_enable_flag();
    void test_vmcs_guest_rflags_direction_flag();
    void test_vmcs_guest_rflags_overflow_flag();
    void test_vmcs_guest_rflags_privilege_level();
    void test_vmcs_guest_rflags_nested_task();
    void test_vmcs_guest_rflags_resume_flag();
    void test_vmcs_guest_rflags_virtual_8086_mode();
    void test_vmcs_guest_rflags_alignment_check_access_control();
    void test_vmcs_guest_rflags_virtual_interupt_flag();
    void test_vmcs_guest_rflags_virtual_interupt_pending();
    void test_vmcs_guest_rflags_id_flag();
    void test_vmcs_guest_rflags_reserved();
    void test_vmcs_guest_rflags_always_disabled();
    void test_vmcs_guest_rflags_always_enabled();
    void test_vmcs_guest_cr0();
    void test_vmcs_guest_cr0_protection_enable();
    void test_vmcs_guest_cr0_monitor_coprocessor();
    void test_vmcs_guest_cr0_emulation();
    void test_vmcs_guest_cr0_task_switched();
    void test_vmcs_guest_cr0_extension_type();
    void test_vmcs_guest_cr0_numeric_error();
    void test_vmcs_guest_cr0_write_protect();
    void test_vmcs_guest_cr0_alignment_mask();
    void test_vmcs_guest_cr0_not_write_through();
    void test_vmcs_guest_cr0_cache_disable();
    void test_vmcs_guest_cr0_paging();
    void test_vmcs_guest_cr3();
    void test_vmcs_guest_cr4();
    void test_vmcs_guest_cr4_v8086_mode_extensions();
    void test_vmcs_guest_cr4_protected_mode_virtual_interrupts();
    void test_vmcs_guest_cr4_time_stamp_disable();
    void test_vmcs_guest_cr4_debugging_extensions();
    void test_vmcs_guest_cr4_page_size_extensions();
    void test_vmcs_guest_cr4_physical_address_extensions();
    void test_vmcs_guest_cr4_machine_check_enable();
    void test_vmcs_guest_cr4_page_global_enable();
    void test_vmcs_guest_cr4_performance_monitor_counter_enable();
    void test_vmcs_guest_cr4_osfxsr();
    void test_vmcs_guest_cr4_osxmmexcpt();
    void test_vmcs_guest_cr4_vmx_enable_bit();
    void test_vmcs_guest_cr4_smx_enable_bit();
    void test_vmcs_guest_cr4_fsgsbase_enable_bit();
    void test_vmcs_guest_cr4_pcid_enable_bit();
    void test_vmcs_guest_cr4_osxsave();
    void test_vmcs_guest_cr4_smep_enable_bit();
    void test_vmcs_guest_cr4_smap_enable_bit();
    void test_vmcs_guest_cr4_protection_key_enable_bit();
    void test_vmcs_guest_es_base();
    void test_vmcs_guest_cs_base();
    void test_vmcs_guest_ss_base();
    void test_vmcs_guest_ds_base();
    void test_vmcs_guest_fs_base();
    void test_vmcs_guest_gs_base();
    void test_vmcs_guest_ldtr_base();
    void test_vmcs_guest_tr_base();
    void test_vmcs_guest_gdtr_base();
    void test_vmcs_guest_idtr_base();
    void test_vmcs_guest_dr7();
    void test_vmcs_guest_rsp();
    void test_vmcs_guest_rip();
    void test_vmcs_guest_pending_debug_exceptions();
    void test_vmcs_guest_pending_debug_exceptions_b0();
    void test_vmcs_guest_pending_debug_exceptions_b1();
    void test_vmcs_guest_pending_debug_exceptions_b2();
    void test_vmcs_guest_pending_debug_exceptions_b3();
    void test_vmcs_guest_pending_debug_exceptions_reserved();
    void test_vmcs_guest_pending_debug_exceptions_enabled_breakpoint();
    void test_vmcs_guest_pending_debug_exceptions_bs();
    void test_vmcs_guest_pending_debug_exceptions_rtm();
    void test_vmcs_guest_ia32_sysenter_esp();
    void test_vmcs_guest_ia32_sysenter_eip();
    void test_vmcs_host_cr0();
    void test_vmcs_host_cr0_protection_enable();
    void test_vmcs_host_cr0_monitor_coprocessor();
    void test_vmcs_host_cr0_emulation();
    void test_vmcs_host_cr0_task_switched();
    void test_vmcs_host_cr0_extension_type();
    void test_vmcs_host_cr0_numeric_error();
    void test_vmcs_host_cr0_write_protect();
    void test_vmcs_host_cr0_alignment_mask();
    void test_vmcs_host_cr0_not_write_through();
    void test_vmcs_host_cr0_cache_disable();
    void test_vmcs_host_cr0_paging();
    void test_vmcs_host_cr3();
    void test_vmcs_host_cr4();
    void test_vmcs_host_cr4_v8086_mode_extensions();
    void test_vmcs_host_cr4_protected_mode_virtual_interrupts();
    void test_vmcs_host_cr4_time_stamp_disable();
    void test_vmcs_host_cr4_debugging_extensions();
    void test_vmcs_host_cr4_page_size_extensions();
    void test_vmcs_host_cr4_physical_address_extensions();
    void test_vmcs_host_cr4_machine_check_enable();
    void test_vmcs_host_cr4_page_global_enable();
    void test_vmcs_host_cr4_performance_monitor_counter_enable();
    void test_vmcs_host_cr4_osfxsr();
    void test_vmcs_host_cr4_osxmmexcpt();
    void test_vmcs_host_cr4_vmx_enable_bit();
    void test_vmcs_host_cr4_smx_enable_bit();
    void test_vmcs_host_cr4_fsgsbase_enable_bit();
    void test_vmcs_host_cr4_pcid_enable_bit();
    void test_vmcs_host_cr4_osxsave();
    void test_vmcs_host_cr4_smep_enable_bit();
    void test_vmcs_host_cr4_smap_enable_bit();
    void test_vmcs_host_cr4_protection_key_enable_bit();
    void test_vmcs_host_fs_base();
    void test_vmcs_host_gs_base();
    void test_vmcs_host_tr_base();
    void test_vmcs_host_gdtr_base();
    void test_vmcs_host_idtr_base();
    void test_vmcs_host_ia32_sysenter_esp();
    void test_vmcs_host_ia32_sysenter_eip();
    void test_vmcs_host_rsp();
    void test_vmcs_host_rip();
    void test_vmcs_host_ia32_pat();
    void test_vmcs_host_ia32_pat_pa0();
    void test_vmcs_host_ia32_pat_pa0_memory_type();
    void test_vmcs_host_ia32_pat_pa0_reserved();
    void test_vmcs_host_ia32_pat_pa1();
    void test_vmcs_host_ia32_pat_pa1_memory_type();
    void test_vmcs_host_ia32_pat_pa1_reserved();
    void test_vmcs_host_ia32_pat_pa2();
    void test_vmcs_host_ia32_pat_pa2_memory_type();
    void test_vmcs_host_ia32_pat_pa2_reserved();
    void test_vmcs_host_ia32_pat_pa3();
    void test_vmcs_host_ia32_pat_pa3_memory_type();
    void test_vmcs_host_ia32_pat_pa3_reserved();
    void test_vmcs_host_ia32_pat_pa4();
    void test_vmcs_host_ia32_pat_pa4_memory_type();
    void test_vmcs_host_ia32_pat_pa4_reserved();
    void test_vmcs_host_ia32_pat_pa5();
    void test_vmcs_host_ia32_pat_pa5_memory_type();
    void test_vmcs_host_ia32_pat_pa5_reserved();
    void test_vmcs_host_ia32_pat_pa6();
    void test_vmcs_host_ia32_pat_pa6_memory_type();
    void test_vmcs_host_ia32_pat_pa6_reserved();
    void test_vmcs_host_ia32_pat_pa7();
    void test_vmcs_host_ia32_pat_pa7_memory_type();
    void test_vmcs_host_ia32_pat_pa7_reserved();
    void test_vmcs_host_ia32_efer();
    void test_vmcs_host_ia32_efer_sce();
    void test_vmcs_host_ia32_efer_lme();
    void test_vmcs_host_ia32_efer_lma();
    void test_vmcs_host_ia32_efer_nxe();
    void test_vmcs_host_ia32_efer_reserved();
    void test_vmcs_host_ia32_perf_global_ctrl();
    void test_vmcs_host_ia32_perf_global_ctrl_reserved();
    void test_vmcs_guest_es_limit();
    void test_vmcs_guest_cs_limit();
    void test_vmcs_guest_ss_limit();
    void test_vmcs_guest_ds_limit();
    void test_vmcs_guest_fs_limit();
    void test_vmcs_guest_gs_limit();
    void test_vmcs_guest_ldtr_limit();
    void test_vmcs_guest_tr_limit();
    void test_vmcs_guest_gdtr_limit();
    void test_vmcs_guest_idtr_limit();
    void test_vmcs_guest_es_access_rights();
    void test_vmcs_guest_es_access_rights_type();
    void test_vmcs_guest_es_access_rights_s();
    void test_vmcs_guest_es_access_rights_dpl();
    void test_vmcs_guest_es_access_rights_present();
    void test_vmcs_guest_es_access_rights_avl();
    void test_vmcs_guest_es_access_rights_l();
    void test_vmcs_guest_es_access_rights_db();
    void test_vmcs_guest_es_access_rights_granularity();
    void test_vmcs_guest_es_access_rights_reserved();
    void test_vmcs_guest_es_access_rights_unusable();
    void test_vmcs_guest_cs_access_rights();
    void test_vmcs_guest_cs_access_rights_type();
    void test_vmcs_guest_cs_access_rights_s();
    void test_vmcs_guest_cs_access_rights_dpl();
    void test_vmcs_guest_cs_access_rights_present();
    void test_vmcs_guest_cs_access_rights_avl();
    void test_vmcs_guest_cs_access_rights_l();
    void test_vmcs_guest_cs_access_rights_db();
    void test_vmcs_guest_cs_access_rights_granularity();
    void test_vmcs_guest_cs_access_rights_reserved();
    void test_vmcs_guest_cs_access_rights_unusable();
    void test_vmcs_guest_ss_access_rights();
    void test_vmcs_guest_ss_access_rights_type();
    void test_vmcs_guest_ss_access_rights_s();
    void test_vmcs_guest_ss_access_rights_dpl();
    void test_vmcs_guest_ss_access_rights_present();
    void test_vmcs_guest_ss_access_rights_avl();
    void test_vmcs_guest_ss_access_rights_l();
    void test_vmcs_guest_ss_access_rights_db();
    void test_vmcs_guest_ss_access_rights_granularity();
    void test_vmcs_guest_ss_access_rights_reserved();
    void test_vmcs_guest_ss_access_rights_unusable();
    void test_vmcs_guest_ds_access_rights();
    void test_vmcs_guest_ds_access_rights_type();
    void test_vmcs_guest_ds_access_rights_s();
    void test_vmcs_guest_ds_access_rights_dpl();
    void test_vmcs_guest_ds_access_rights_present();
    void test_vmcs_guest_ds_access_rights_avl();
    void test_vmcs_guest_ds_access_rights_l();
    void test_vmcs_guest_ds_access_rights_db();
    void test_vmcs_guest_ds_access_rights_granularity();
    void test_vmcs_guest_ds_access_rights_reserved();
    void test_vmcs_guest_ds_access_rights_unusable();
    void test_vmcs_guest_fs_access_rights();
    void test_vmcs_guest_fs_access_rights_type();
    void test_vmcs_guest_fs_access_rights_s();
    void test_vmcs_guest_fs_access_rights_dpl();
    void test_vmcs_guest_fs_access_rights_present();
    void test_vmcs_guest_fs_access_rights_avl();
    void test_vmcs_guest_fs_access_rights_l();
    void test_vmcs_guest_fs_access_rights_db();
    void test_vmcs_guest_fs_access_rights_granularity();
    void test_vmcs_guest_fs_access_rights_reserved();
    void test_vmcs_guest_fs_access_rights_unusable();
    void test_vmcs_guest_gs_access_rights();
    void test_vmcs_guest_gs_access_rights_type();
    void test_vmcs_guest_gs_access_rights_s();
    void test_vmcs_guest_gs_access_rights_dpl();
    void test_vmcs_guest_gs_access_rights_present();
    void test_vmcs_guest_gs_access_rights_avl();
    void test_vmcs_guest_gs_access_rights_l();
    void test_vmcs_guest_gs_access_rights_db();
    void test_vmcs_guest_gs_access_rights_granularity();
    void test_vmcs_guest_gs_access_rights_reserved();
    void test_vmcs_guest_gs_access_rights_unusable();
    void test_vmcs_guest_ldtr_access_rights();
    void test_vmcs_guest_ldtr_access_rights_type();
    void test_vmcs_guest_ldtr_access_rights_s();
    void test_vmcs_guest_ldtr_access_rights_dpl();
    void test_vmcs_guest_ldtr_access_rights_present();
    void test_vmcs_guest_ldtr_access_rights_avl();
    void test_vmcs_guest_ldtr_access_rights_l();
    void test_vmcs_guest_ldtr_access_rights_db();
    void test_vmcs_guest_ldtr_access_rights_granularity();
    void test_vmcs_guest_ldtr_access_rights_reserved();
    void test_vmcs_guest_ldtr_access_rights_unusable();
    void test_vmcs_guest_tr_access_rights();
    void test_vmcs_guest_tr_access_rights_type();
    void test_vmcs_guest_tr_access_rights_s();
    void test_vmcs_guest_tr_access_rights_dpl();
    void test_vmcs_guest_tr_access_rights_present();
    void test_vmcs_guest_tr_access_rights_avl();
    void test_vmcs_guest_tr_access_rights_l();
    void test_vmcs_guest_tr_access_rights_db();
    void test_vmcs_guest_tr_access_rights_granularity();
    void test_vmcs_guest_tr_access_rights_reserved();
    void test_vmcs_guest_tr_access_rights_unusable();
    void test_vmcs_guest_interruptibility_state();
    void test_vmcs_guest_interruptibility_state_blocking_by_sti();
    void test_vmcs_guest_interruptibility_state_blocking_by_mov_ss();
    void test_vmcs_guest_interruptibility_state_blocking_by_smi();
    void test_vmcs_guest_interruptibility_state_blocking_by_nmi();
    void test_vmcs_guest_interruptibility_state_enclave_interruption();
    void test_vmcs_guest_interruptibility_state_reserved();
    void test_vmcs_guest_activity_state();
    void test_vmcs_guest_smbase();
    void test_vmcs_guest_ia32_sysenter_cs();
    void test_vmcs_vmx_preemption_timer_value();
    void test_vmcs_host_ia32_sysenter_cs();
    void test_vmcs_cr0_guest_host_mask();
    void test_vmcs_cr4_guest_host_mask();
    void test_vmcs_cr0_read_shadow();
    void test_vmcs_cr4_read_shadow();
    void test_vmcs_cr3_target_value_0();
    void test_vmcs_cr3_target_value_1();
    void test_vmcs_cr3_target_value_2();
    void test_vmcs_cr3_target_value_3();
    void test_vmcs_pin_based_vm_execution_controls();
    void test_vmcs_pin_based_vm_execution_controls_external_interrupt_exiting();
    void test_vmcs_pin_based_vm_execution_controls_nmi_exiting();
    void test_vmcs_pin_based_vm_execution_controls_virtual_nmis();
    void test_vmcs_pin_based_vm_execution_controls_activate_vmx_preemption_timer();
    void test_vmcs_pin_based_vm_execution_controls_process_posted_interrupts();
    void test_vmcs_primary_processor_based_vm_execution_controls();
    void test_vmcs_primary_processor_based_vm_execution_controls_interrupt_window_exiting();
    void test_vmcs_primary_processor_based_vm_execution_controls_use_tsc_offsetting();
    void test_vmcs_primary_processor_based_vm_execution_controls_hlt_exiting();
    void test_vmcs_primary_processor_based_vm_execution_controls_invlpg_exiting();
    void test_vmcs_primary_processor_based_vm_execution_controls_mwait_exiting();
    void test_vmcs_primary_processor_based_vm_execution_controls_rdpmc_exiting();
    void test_vmcs_primary_processor_based_vm_execution_controls_rdtsc_exiting();
    void test_vmcs_primary_processor_based_vm_execution_controls_cr3_load_exiting();
    void test_vmcs_primary_processor_based_vm_execution_controls_cr3_store_exiting();
    void test_vmcs_primary_processor_based_vm_execution_controls_cr8_load_exiting();
    void test_vmcs_primary_processor_based_vm_execution_controls_cr8_store_exiting();
    void test_vmcs_primary_processor_based_vm_execution_controls_use_tpr_shadow();
    void test_vmcs_primary_processor_based_vm_execution_controls_nmi_window_exiting();
    void test_vmcs_primary_processor_based_vm_execution_controls_mov_dr_exiting();
    void test_vmcs_primary_processor_based_vm_execution_controls_unconditional_io_exiting();
    void test_vmcs_primary_processor_based_vm_execution_controls_use_io_bitmaps();
    void test_vmcs_primary_processor_based_vm_execution_controls_monitor_trap_flag();
    void test_vmcs_primary_processor_based_vm_execution_controls_use_msr_bitmap();
    void test_vmcs_primary_processor_based_vm_execution_controls_monitor_exiting();
    void test_vmcs_primary_processor_based_vm_execution_controls_pause_exiting();
    void test_vmcs_primary_processor_based_vm_execution_controls_activate_secondary_controls();
    void test_vmcs_exception_bitmap();
    void test_vmcs_page_fault_error_code_mask();
    void test_vmcs_page_fault_error_code_match();
    void test_vmcs_cr3_target_count();
    void test_vmcs_vm_exit_controls();
    void test_vmcs_vm_exit_controls_save_debug_controls();
    void test_vmcs_vm_exit_controls_host_address_space_size();
    void test_vmcs_vm_exit_controls_load_ia32_perf_global_ctrl();
    void test_vmcs_vm_exit_controls_acknowledge_interrupt_on_exit();
    void test_vmcs_vm_exit_controls_save_ia32_pat();
    void test_vmcs_vm_exit_controls_load_ia32_pat();
    void test_vmcs_vm_exit_controls_save_ia32_efer();
    void test_vmcs_vm_exit_controls_load_ia32_efer();
    void test_vmcs_vm_exit_controls_save_vmx_preemption_timer_value();
    void test_vmcs_vm_exit_controls_clear_ia32_bndcfgs();
    void test_vmcs_vm_exit_msr_store_count();
    void test_vmcs_vm_exit_msr_load_count();
    void test_vmcs_vm_entry_controls();
    void test_vmcs_vm_entry_controls_load_debug_controls();
    void test_vmcs_vm_entry_controls_ia_32e_mode_guest();
    void test_vmcs_vm_entry_controls_entry_to_smm();
    void test_vmcs_vm_entry_controls_deactivate_dual_monitor_treatment();
    void test_vmcs_vm_entry_controls_load_ia32_perf_global_ctrl();
    void test_vmcs_vm_entry_controls_load_ia32_pat();
    void test_vmcs_vm_entry_controls_load_ia32_efer();
    void test_vmcs_vm_entry_controls_load_ia32_bndcfgs();
    void test_vmcs_vm_entry_msr_load_count();
    void test_vmcs_vm_entry_interruption_information_field();
    void test_vmcs_vm_entry_interruption_information_field_vector();
    void test_vmcs_vm_entry_interruption_information_field_type();
    void test_vmcs_vm_entry_interruption_information_field_deliver_error_code_bit();
    void test_vmcs_vm_entry_interruption_information_field_reserved();
    void test_vmcs_vm_entry_interruption_information_field_valid_bit();
    void test_vmcs_vm_entry_exception_error_code();
    void test_vmcs_vm_entry_instruction_length();
    void test_vmcs_tpr_threshold();
    void test_vmcs_secondary_processor_based_vm_execution_controls();
    void test_vmcs_secondary_processor_based_vm_execution_controls_virtualize_apic_accesses();
    void test_vmcs_secondary_processor_based_vm_execution_controls_enable_ept();
    void test_vmcs_secondary_processor_based_vm_execution_controls_descriptor_table_exiting();
    void test_vmcs_secondary_processor_based_vm_execution_controls_enable_rdtscp();
    void test_vmcs_secondary_processor_based_vm_execution_controls_virtualize_x2apic_mode();
    void test_vmcs_secondary_processor_based_vm_execution_controls_enable_vpid();
    void test_vmcs_secondary_processor_based_vm_execution_controls_wbinvd_exiting();
    void test_vmcs_secondary_processor_based_vm_execution_controls_unrestricted_guest();
    void test_vmcs_secondary_processor_based_vm_execution_controls_apic_register_virtualization();
    void test_vmcs_secondary_processor_based_vm_execution_controls_virtual_interrupt_delivery();
    void test_vmcs_secondary_processor_based_vm_execution_controls_pause_loop_exiting();
    void test_vmcs_secondary_processor_based_vm_execution_controls_rdrand_exiting();
    void test_vmcs_secondary_processor_based_vm_execution_controls_enable_invpcid();
    void test_vmcs_secondary_processor_based_vm_execution_controls_enable_vm_functions();
    void test_vmcs_secondary_processor_based_vm_execution_controls_vmcs_shadowing();
    void test_vmcs_secondary_processor_based_vm_execution_controls_rdseed_exiting();
    void test_vmcs_secondary_processor_based_vm_execution_controls_enable_pml();
    void test_vmcs_secondary_processor_based_vm_execution_controls_ept_violation_ve();
    void test_vmcs_secondary_processor_based_vm_execution_controls_enable_xsaves_xrstors();
    void test_vmcs_ple_gap();
    void test_vmcs_ple_window();
    void test_vmcs_vm_instruction_error();
    void test_vmcs_exit_reason();
    void test_vmcs_exit_reason_basic_exit_reason();
    void test_vmcs_exit_reason_basic_exit_reason_description();
    void test_vmcs_exit_reason_basic_exit_reason_description_if_exists();
    void test_vmcs_exit_reason_reserved();
    void test_vmcs_exit_reason_vm_exit_incident_to_enclave_mode();
    void test_vmcs_exit_reason_pending_mtf_vm_exit();
    void test_vmcs_exit_reason_vm_exit_from_vmx_root_operation();
    void test_vmcs_exit_reason_vm_entry_failure();
    void test_vmcs_vm_exit_interruption_information();
    void test_vmcs_vm_exit_interruption_information_vector();
    void test_vmcs_vm_exit_interruption_information_interruption_type();
    void test_vmcs_vm_exit_interruption_information_error_code_valid();
    void test_vmcs_vm_exit_interruption_information_nmi_blocking_due_to_iret();
    void test_vmcs_vm_exit_interruption_information_reserved();
    void test_vmcs_vm_exit_interruption_information_valid_bit();
    void test_vmcs_vm_exit_interruption_error_code();
    void test_vmcs_idt_vectoring_information();
    void test_vmcs_idt_vectoring_information_vector();
    void test_vmcs_idt_vectoring_information_interruption_type();
    void test_vmcs_idt_vectoring_information_error_code_valid();
    void test_vmcs_idt_vectoring_information_reserved();
    void test_vmcs_idt_vectoring_information_valid_bit();
    void test_vmcs_idt_vectoring_error_code();
    void test_vmcs_vm_exit_instruction_length();
    void test_vmcs_vm_exit_instruction_information();
    void test_vmcs_vm_exit_instruction_information_ins();
    void test_vmcs_vm_exit_instruction_information_ins_address_size();
    void test_vmcs_vm_exit_instruction_information_outs();
    void test_vmcs_vm_exit_instruction_information_outs_address_size();
    void test_vmcs_vm_exit_instruction_information_outs_segment_register();
    void test_vmcs_vm_exit_instruction_information_invept();
    void test_vmcs_vm_exit_instruction_information_invept_scaling();
    void test_vmcs_vm_exit_instruction_information_invept_address_size();
    void test_vmcs_vm_exit_instruction_information_invept_segment_register();
    void test_vmcs_vm_exit_instruction_information_invept_index_reg();
    void test_vmcs_vm_exit_instruction_information_invept_index_reg_invalid();
    void test_vmcs_vm_exit_instruction_information_invept_base_reg();
    void test_vmcs_vm_exit_instruction_information_invept_base_reg_invalid();
    void test_vmcs_vm_exit_instruction_information_invept_reg2();
    void test_vmcs_vm_exit_instruction_information_invpcid();
    void test_vmcs_vm_exit_instruction_information_invpcid_scaling();
    void test_vmcs_vm_exit_instruction_information_invpcid_address_size();
    void test_vmcs_vm_exit_instruction_information_invpcid_segment_register();
    void test_vmcs_vm_exit_instruction_information_invpcid_index_reg();
    void test_vmcs_vm_exit_instruction_information_invpcid_index_reg_invalid();
    void test_vmcs_vm_exit_instruction_information_invpcid_base_reg();
    void test_vmcs_vm_exit_instruction_information_invpcid_base_reg_invalid();
    void test_vmcs_vm_exit_instruction_information_invpcid_reg2();
    void test_vmcs_vm_exit_instruction_information_invvpid();
    void test_vmcs_vm_exit_instruction_information_invvpid_scaling();
    void test_vmcs_vm_exit_instruction_information_invvpid_address_size();
    void test_vmcs_vm_exit_instruction_information_invvpid_segment_register();
    void test_vmcs_vm_exit_instruction_information_invvpid_index_reg();
    void test_vmcs_vm_exit_instruction_information_invvpid_index_reg_invalid();
    void test_vmcs_vm_exit_instruction_information_invvpid_base_reg();
    void test_vmcs_vm_exit_instruction_information_invvpid_base_reg_invalid();
    void test_vmcs_vm_exit_instruction_information_invvpid_reg2();
    void test_vmcs_vm_exit_instruction_information_lidt();
    void test_vmcs_vm_exit_instruction_information_lidt_scaling();
    void test_vmcs_vm_exit_instruction_information_lidt_address_size();
    void test_vmcs_vm_exit_instruction_information_lidt_operand_size();
    void test_vmcs_vm_exit_instruction_information_lidt_segment_register();
    void test_vmcs_vm_exit_instruction_information_lidt_index_reg();
    void test_vmcs_vm_exit_instruction_information_lidt_index_reg_invalid();
    void test_vmcs_vm_exit_instruction_information_lidt_base_reg();
    void test_vmcs_vm_exit_instruction_information_lidt_base_reg_invalid();
    void test_vmcs_vm_exit_instruction_information_lidt_instruction_identity();
    void test_vmcs_vm_exit_instruction_information_lgdt();
    void test_vmcs_vm_exit_instruction_information_lgdt_scaling();
    void test_vmcs_vm_exit_instruction_information_lgdt_address_size();
    void test_vmcs_vm_exit_instruction_information_lgdt_operand_size();
    void test_vmcs_vm_exit_instruction_information_lgdt_segment_register();
    void test_vmcs_vm_exit_instruction_information_lgdt_index_reg();
    void test_vmcs_vm_exit_instruction_information_lgdt_index_reg_invalid();
    void test_vmcs_vm_exit_instruction_information_lgdt_base_reg();
    void test_vmcs_vm_exit_instruction_information_lgdt_base_reg_invalid();
    void test_vmcs_vm_exit_instruction_information_lgdt_instruction_identity();
    void test_vmcs_vm_exit_instruction_information_sidt();
    void test_vmcs_vm_exit_instruction_information_sidt_scaling();
    void test_vmcs_vm_exit_instruction_information_sidt_address_size();
    void test_vmcs_vm_exit_instruction_information_sidt_operand_size();
    void test_vmcs_vm_exit_instruction_information_sidt_segment_register();
    void test_vmcs_vm_exit_instruction_information_sidt_index_reg();
    void test_vmcs_vm_exit_instruction_information_sidt_index_reg_invalid();
    void test_vmcs_vm_exit_instruction_information_sidt_base_reg();
    void test_vmcs_vm_exit_instruction_information_sidt_base_reg_invalid();
    void test_vmcs_vm_exit_instruction_information_sidt_instruction_identity();
    void test_vmcs_vm_exit_instruction_information_sgdt();
    void test_vmcs_vm_exit_instruction_information_sgdt_scaling();
    void test_vmcs_vm_exit_instruction_information_sgdt_address_size();
    void test_vmcs_vm_exit_instruction_information_sgdt_operand_size();
    void test_vmcs_vm_exit_instruction_information_sgdt_segment_register();
    void test_vmcs_vm_exit_instruction_information_sgdt_index_reg();
    void test_vmcs_vm_exit_instruction_information_sgdt_index_reg_invalid();
    void test_vmcs_vm_exit_instruction_information_sgdt_base_reg();
    void test_vmcs_vm_exit_instruction_information_sgdt_base_reg_invalid();
    void test_vmcs_vm_exit_instruction_information_sgdt_instruction_identity();
    void test_vmcs_vm_exit_instruction_information_lldt();
    void test_vmcs_vm_exit_instruction_information_lldt_scaling();
    void test_vmcs_vm_exit_instruction_information_lldt_reg1();
    void test_vmcs_vm_exit_instruction_information_lldt_address_size();
    void test_vmcs_vm_exit_instruction_information_lldt_mem_reg();
    void test_vmcs_vm_exit_instruction_information_lldt_segment_register();
    void test_vmcs_vm_exit_instruction_information_lldt_index_reg();
    void test_vmcs_vm_exit_instruction_information_lldt_index_reg_invalid();
    void test_vmcs_vm_exit_instruction_information_lldt_base_reg();
    void test_vmcs_vm_exit_instruction_information_lldt_base_reg_invalid();
    void test_vmcs_vm_exit_instruction_information_lldt_instruction_identity();
    void test_vmcs_vm_exit_instruction_information_ltr();
    void test_vmcs_vm_exit_instruction_information_ltr_scaling();
    void test_vmcs_vm_exit_instruction_information_ltr_reg1();
    void test_vmcs_vm_exit_instruction_information_ltr_address_size();
    void test_vmcs_vm_exit_instruction_information_ltr_mem_reg();
    void test_vmcs_vm_exit_instruction_information_ltr_segment_register();
    void test_vmcs_vm_exit_instruction_information_ltr_index_reg();
    void test_vmcs_vm_exit_instruction_information_ltr_index_reg_invalid();
    void test_vmcs_vm_exit_instruction_information_ltr_base_reg();
    void test_vmcs_vm_exit_instruction_information_ltr_base_reg_invalid();
    void test_vmcs_vm_exit_instruction_information_ltr_instruction_identity();
    void test_vmcs_vm_exit_instruction_information_sldt();
    void test_vmcs_vm_exit_instruction_information_sldt_scaling();
    void test_vmcs_vm_exit_instruction_information_sldt_reg1();
    void test_vmcs_vm_exit_instruction_information_sldt_address_size();
    void test_vmcs_vm_exit_instruction_information_sldt_mem_reg();
    void test_vmcs_vm_exit_instruction_information_sldt_segment_register();
    void test_vmcs_vm_exit_instruction_information_sldt_index_reg();
    void test_vmcs_vm_exit_instruction_information_sldt_index_reg_invalid();
    void test_vmcs_vm_exit_instruction_information_sldt_base_reg();
    void test_vmcs_vm_exit_instruction_information_sldt_base_reg_invalid();
    void test_vmcs_vm_exit_instruction_information_sldt_instruction_identity();
    void test_vmcs_vm_exit_instruction_information_str();
    void test_vmcs_vm_exit_instruction_information_str_scaling();
    void test_vmcs_vm_exit_instruction_information_str_reg1();
    void test_vmcs_vm_exit_instruction_information_str_address_size();
    void test_vmcs_vm_exit_instruction_information_str_mem_reg();
    void test_vmcs_vm_exit_instruction_information_str_segment_register();
    void test_vmcs_vm_exit_instruction_information_str_index_reg();
    void test_vmcs_vm_exit_instruction_information_str_index_reg_invalid();
    void test_vmcs_vm_exit_instruction_information_str_base_reg();
    void test_vmcs_vm_exit_instruction_information_str_base_reg_invalid();
    void test_vmcs_vm_exit_instruction_information_str_instruction_identity();
    void test_vmcs_vm_exit_instruction_information_rdrand();
    void test_vmcs_vm_exit_instruction_information_rdrand_destination_register();
    void test_vmcs_vm_exit_instruction_information_rdrand_operand_size();
    void test_vmcs_vm_exit_instruction_information_rdseed();
    void test_vmcs_vm_exit_instruction_information_rdseed_destination_register();
    void test_vmcs_vm_exit_instruction_information_rdseed_operand_size();
    void test_vmcs_vm_exit_instruction_information_vmclear();
    void test_vmcs_vm_exit_instruction_information_vmclear_scaling();
    void test_vmcs_vm_exit_instruction_information_vmclear_address_size();
    void test_vmcs_vm_exit_instruction_information_vmclear_segment_register();
    void test_vmcs_vm_exit_instruction_information_vmclear_index_reg();
    void test_vmcs_vm_exit_instruction_information_vmclear_index_reg_invalid();
    void test_vmcs_vm_exit_instruction_information_vmclear_base_reg();
    void test_vmcs_vm_exit_instruction_information_vmclear_base_reg_invalid();
    void test_vmcs_vm_exit_instruction_information_vmptrld();
    void test_vmcs_vm_exit_instruction_information_vmptrld_scaling();
    void test_vmcs_vm_exit_instruction_information_vmptrld_address_size();
    void test_vmcs_vm_exit_instruction_information_vmptrld_segment_register();
    void test_vmcs_vm_exit_instruction_information_vmptrld_index_reg();
    void test_vmcs_vm_exit_instruction_information_vmptrld_index_reg_invalid();
    void test_vmcs_vm_exit_instruction_information_vmptrld_base_reg();
    void test_vmcs_vm_exit_instruction_information_vmptrld_base_reg_invalid();
    void test_vmcs_vm_exit_instruction_information_vmptrst();
    void test_vmcs_vm_exit_instruction_information_vmptrst_scaling();
    void test_vmcs_vm_exit_instruction_information_vmptrst_address_size();
    void test_vmcs_vm_exit_instruction_information_vmptrst_segment_register();
    void test_vmcs_vm_exit_instruction_information_vmptrst_index_reg();
    void test_vmcs_vm_exit_instruction_information_vmptrst_index_reg_invalid();
    void test_vmcs_vm_exit_instruction_information_vmptrst_base_reg();
    void test_vmcs_vm_exit_instruction_information_vmptrst_base_reg_invalid();
    void test_vmcs_vm_exit_instruction_information_vmxon();
    void test_vmcs_vm_exit_instruction_information_vmxon_scaling();
    void test_vmcs_vm_exit_instruction_information_vmxon_address_size();
    void test_vmcs_vm_exit_instruction_information_vmxon_segment_register();
    void test_vmcs_vm_exit_instruction_information_vmxon_index_reg();
    void test_vmcs_vm_exit_instruction_information_vmxon_index_reg_invalid();
    void test_vmcs_vm_exit_instruction_information_vmxon_base_reg();
    void test_vmcs_vm_exit_instruction_information_vmxon_base_reg_invalid();
    void test_vmcs_vm_exit_instruction_information_xrstors();
    void test_vmcs_vm_exit_instruction_information_xrstors_scaling();
    void test_vmcs_vm_exit_instruction_information_xrstors_address_size();
    void test_vmcs_vm_exit_instruction_information_xrstors_segment_register();
    void test_vmcs_vm_exit_instruction_information_xrstors_index_reg();
    void test_vmcs_vm_exit_instruction_information_xrstors_index_reg_invalid();
    void test_vmcs_vm_exit_instruction_information_xrstors_base_reg();
    void test_vmcs_vm_exit_instruction_information_xrstors_base_reg_invalid();
    void test_vmcs_vm_exit_instruction_information_xsaves();
    void test_vmcs_vm_exit_instruction_information_xsaves_scaling();
    void test_vmcs_vm_exit_instruction_information_xsaves_address_size();
    void test_vmcs_vm_exit_instruction_information_xsaves_segment_register();
    void test_vmcs_vm_exit_instruction_information_xsaves_index_reg();
    void test_vmcs_vm_exit_instruction_information_xsaves_index_reg_invalid();
    void test_vmcs_vm_exit_instruction_information_xsaves_base_reg();
    void test_vmcs_vm_exit_instruction_information_xsaves_base_reg_invalid();
    void test_vmcs_vm_exit_instruction_information_vmread();
    void test_vmcs_vm_exit_instruction_information_vmread_scaling();
    void test_vmcs_vm_exit_instruction_information_vmread_reg1();
    void test_vmcs_vm_exit_instruction_information_vmread_address_size();
    void test_vmcs_vm_exit_instruction_information_vmread_mem_reg();
    void test_vmcs_vm_exit_instruction_information_vmread_segment_register();
    void test_vmcs_vm_exit_instruction_information_vmread_index_reg();
    void test_vmcs_vm_exit_instruction_information_vmread_index_reg_invalid();
    void test_vmcs_vm_exit_instruction_information_vmread_base_reg();
    void test_vmcs_vm_exit_instruction_information_vmread_base_reg_invalid();
    void test_vmcs_vm_exit_instruction_information_vmread_reg2();
    void test_vmcs_vm_exit_instruction_information_vmwrite();
    void test_vmcs_vm_exit_instruction_information_vmwrite_scaling();
    void test_vmcs_vm_exit_instruction_information_vmwrite_reg1();
    void test_vmcs_vm_exit_instruction_information_vmwrite_address_size();
    void test_vmcs_vm_exit_instruction_information_vmwrite_mem_reg();
    void test_vmcs_vm_exit_instruction_information_vmwrite_segment_register();
    void test_vmcs_vm_exit_instruction_information_vmwrite_index_reg();
    void test_vmcs_vm_exit_instruction_information_vmwrite_index_reg_invalid();
    void test_vmcs_vm_exit_instruction_information_vmwrite_base_reg();
    void test_vmcs_vm_exit_instruction_information_vmwrite_base_reg_invalid();
    void test_vmcs_vm_exit_instruction_information_vmwrite_reg2();
    void test_vmcs_exit_qualification();
    void test_vmcs_exit_qualification_debug_exception();
    void test_vmcs_exit_qualification_debug_exception_b0();
    void test_vmcs_exit_qualification_debug_exception_b1();
    void test_vmcs_exit_qualification_debug_exception_b2();
    void test_vmcs_exit_qualification_debug_exception_b3();
    void test_vmcs_exit_qualification_debug_exception_reserved();
    void test_vmcs_exit_qualification_debug_exception_bd();
    void test_vmcs_exit_qualification_debug_exception_bs();
    void test_vmcs_exit_qualification_page_fault_exception();
    void test_vmcs_exit_qualification_sipi();
    void test_vmcs_exit_qualification_sipi_vector();
    void test_vmcs_exit_qualification_task_switch();
    void test_vmcs_exit_qualification_task_switch_tss_selector();
    void test_vmcs_exit_qualification_task_switch_reserved();
    void test_vmcs_exit_qualification_task_switch_source_of_task_switch_init();
    void test_vmcs_exit_qualification_invept();
    void test_vmcs_exit_qualification_invpcid();
    void test_vmcs_exit_qualification_invvpid();
    void test_vmcs_exit_qualification_lgdt();
    void test_vmcs_exit_qualification_lidt();
    void test_vmcs_exit_qualification_lldt();
    void test_vmcs_exit_qualification_ltr();
    void test_vmcs_exit_qualification_sgdt();
    void test_vmcs_exit_qualification_sidt();
    void test_vmcs_exit_qualification_sldt();
    void test_vmcs_exit_qualification_str();
    void test_vmcs_exit_qualification_vmclear();
    void test_vmcs_exit_qualification_vmptrld();
    void test_vmcs_exit_qualification_vmread();
    void test_vmcs_exit_qualification_vmwrite();
    void test_vmcs_exit_qualification_vmxon();
    void test_vmcs_exit_qualification_xrstors();
    void test_vmcs_exit_qualification_xsaves();
    void test_vmcs_exit_qualification_control_register_access();
    void test_vmcs_exit_qualification_control_register_access_control_register_number();
    void test_vmcs_exit_qualification_control_register_access_access_type();
    void test_vmcs_exit_qualification_control_register_access_lmsw_operand_type();
    void test_vmcs_exit_qualification_control_register_access_reserved();
    void test_vmcs_exit_qualification_control_register_access_general_purpose_register();
    void test_vmcs_exit_qualification_control_register_access_source_data();
    void test_vmcs_exit_qualification_mov_dr();
    void test_vmcs_exit_qualification_mov_dr_debug_register_number();
    void test_vmcs_exit_qualification_mov_dr_reserved();
    void test_vmcs_exit_qualification_mov_dr_direction_of_access();
    void test_vmcs_exit_qualification_mov_dr_general_purpose_register();
    void test_vmcs_exit_qualification_io_instruction();
    void test_vmcs_exit_qualification_io_instruction_size_of_access();
    void test_vmcs_exit_qualification_io_instruction_direction_of_access();
    void test_vmcs_exit_qualification_io_instruction_string_instruction();
    void test_vmcs_exit_qualification_io_instruction_rep_prefixed();
    void test_vmcs_exit_qualification_io_instruction_operand_encoding();
    void test_vmcs_exit_qualification_io_instruction_reserved();
    void test_vmcs_exit_qualification_io_instruction_port_number();
    void test_vmcs_exit_qualification_mwait();
    void test_vmcs_exit_qualification_linear_apic_access();
    void test_vmcs_exit_qualification_linear_apic_access_offset();
    void test_vmcs_exit_qualification_linear_apic_access_access_type();
    void test_vmcs_exit_qualification_linear_apic_access_reserved();
    void test_vmcs_exit_qualification_guest_physical_apic_access();
    void test_vmcs_exit_qualification_guest_physical_apic_access_access_type();
    void test_vmcs_exit_qualification_guest_physical_apic_access_reserved();
    void test_vmcs_exit_qualification_ept_violation();
    void test_vmcs_exit_qualification_ept_violation_data_read();
    void test_vmcs_exit_qualification_ept_violation_data_write();
    void test_vmcs_exit_qualification_ept_violation_instruction_fetch();
    void test_vmcs_exit_qualification_ept_violation_readable();
    void test_vmcs_exit_qualification_ept_violation_writeable();
    void test_vmcs_exit_qualification_ept_violation_executable();
    void test_vmcs_exit_qualification_ept_violation_reserved();
    void test_vmcs_exit_qualification_ept_violation_valid_guest_linear_address();
    void test_vmcs_exit_qualification_ept_violation_nmi_unblocking_due_to_iret();
    void test_vmcs_exit_qualification_eoi_virtualization();
    void test_vmcs_exit_qualification_eoi_virtualization_vector();
    void test_vmcs_exit_qualification_apic_write();
    void test_vmcs_exit_qualification_apic_write_offset();
    void test_vmcs_io_rcx();
    void test_vmcs_io_rsi();
    void test_vmcs_io_rdi();
    void test_vmcs_io_rip();
    void test_vmcs_guest_linear_address();
    void test_vmcs_vmcs_link_pointer();
    void test_vmcs_guest_ia32_debugctl();
    void test_vmcs_guest_ia32_debugctl_lbr();
    void test_vmcs_guest_ia32_debugctl_btf();
    void test_vmcs_guest_ia32_debugctl_tr();
    void test_vmcs_guest_ia32_debugctl_bts();
    void test_vmcs_guest_ia32_debugctl_btint();
    void test_vmcs_guest_ia32_debugctl_bt_off_os();
    void test_vmcs_guest_ia32_debugctl_bt_off_user();
    void test_vmcs_guest_ia32_debugctl_freeze_lbrs_on_pmi();
    void test_vmcs_guest_ia32_debugctl_freeze_perfmon_on_pmi();
    void test_vmcs_guest_ia32_debugctl_enable_uncore_pmi();
    void test_vmcs_guest_ia32_debugctl_freeze_while_smm();
    void test_vmcs_guest_ia32_debugctl_rtm_debug();
    void test_vmcs_guest_ia32_debugctl_reserved();
    void test_vmcs_guest_ia32_pat();
    void test_vmcs_guest_ia32_pat_pa0();
    void test_vmcs_guest_ia32_pat_pa0_memory_type();
    void test_vmcs_guest_ia32_pat_pa0_reserved();
    void test_vmcs_guest_ia32_pat_pa1();
    void test_vmcs_guest_ia32_pat_pa1_memory_type();
    void test_vmcs_guest_ia32_pat_pa1_reserved();
    void test_vmcs_guest_ia32_pat_pa2();
    void test_vmcs_guest_ia32_pat_pa2_memory_type();
    void test_vmcs_guest_ia32_pat_pa2_reserved();
    void test_vmcs_guest_ia32_pat_pa3();
    void test_vmcs_guest_ia32_pat_pa3_memory_type();
    void test_vmcs_guest_ia32_pat_pa3_reserved();
    void test_vmcs_guest_ia32_pat_pa4();
    void test_vmcs_guest_ia32_pat_pa4_memory_type();
    void test_vmcs_guest_ia32_pat_pa4_reserved();
    void test_vmcs_guest_ia32_pat_pa5();
    void test_vmcs_guest_ia32_pat_pa5_memory_type();
    void test_vmcs_guest_ia32_pat_pa5_reserved();
    void test_vmcs_guest_ia32_pat_pa6();
    void test_vmcs_guest_ia32_pat_pa6_memory_type();
    void test_vmcs_guest_ia32_pat_pa6_reserved();
    void test_vmcs_guest_ia32_pat_pa7();
    void test_vmcs_guest_ia32_pat_pa7_memory_type();
    void test_vmcs_guest_ia32_pat_pa7_reserved();
    void test_vmcs_guest_ia32_efer();
    void test_vmcs_guest_ia32_efer_sce();
    void test_vmcs_guest_ia32_efer_lme();
    void test_vmcs_guest_ia32_efer_lma();
    void test_vmcs_guest_ia32_efer_nxe();
    void test_vmcs_guest_ia32_efer_reserved();
    void test_vmcs_guest_ia32_perf_global_ctrl();
    void test_vmcs_guest_ia32_perf_global_ctrl_reserved();
    void test_vmcs_guest_pdpte0();
    void test_vmcs_guest_pdpte0_present();
    void test_vmcs_guest_pdpte0_reserved();
    void test_vmcs_guest_pdpte0_pwt();
    void test_vmcs_guest_pdpte0_pcd();
    void test_vmcs_guest_pdpte0_page_directory_addr();
    void test_vmcs_guest_pdpte1();
    void test_vmcs_guest_pdpte1_present();
    void test_vmcs_guest_pdpte1_reserved();
    void test_vmcs_guest_pdpte1_pwt();
    void test_vmcs_guest_pdpte1_pcd();
    void test_vmcs_guest_pdpte1_page_directory_addr();
    void test_vmcs_guest_pdpte2();
    void test_vmcs_guest_pdpte2_present();
    void test_vmcs_guest_pdpte2_reserved();
    void test_vmcs_guest_pdpte2_pwt();
    void test_vmcs_guest_pdpte2_pcd();
    void test_vmcs_guest_pdpte2_page_directory_addr();
    void test_vmcs_guest_pdpte3();
    void test_vmcs_guest_pdpte3_present();
    void test_vmcs_guest_pdpte3_reserved();
    void test_vmcs_guest_pdpte3_pwt();
    void test_vmcs_guest_pdpte3_pcd();
    void test_vmcs_guest_pdpte3_page_directory_addr();
    void test_vmcs_guest_ia32_bndcfgs();
    void test_vmcs_guest_ia32_bndcfgs_en();
    void test_vmcs_guest_ia32_bndcfgs_bndpreserve();
    void test_vmcs_guest_ia32_bndcfgs_reserved();
    void test_vmcs_guest_ia32_bndcfgs_base_addr_of_bnd_directory();

    void test_check_control_vmx_controls_all();
    void test_check_control_vm_execution_control_fields_all();
    void test_check_control_pin_based_ctls_reserved_properly_set();
    void test_check_control_proc_based_ctls_reserved_properly_set();
    void test_check_control_proc_based_ctls2_reserved_properly_set();
    void test_check_control_cr3_count_less_than_4();
    void test_check_control_io_bitmap_address_bits();
    void test_check_control_msr_bitmap_address_bits();
    void test_check_control_tpr_shadow_and_virtual_apic();
    void test_check_control_nmi_exiting_and_virtual_nmi();
    void test_check_control_virtual_nmi_and_nmi_window();
    void test_check_control_virtual_apic_address_bits();
    void test_check_control_x2apic_mode_and_virtual_apic_access();
    void test_check_control_virtual_interrupt_and_external_interrupt();
    void test_check_control_process_posted_interrupt_checks();
    void test_check_control_vpid_checks();
    void test_check_control_enable_ept_checks();
    void test_check_control_unrestricted_guests();
    void test_check_control_enable_vm_functions();
    void test_check_control_enable_vmcs_shadowing();
    void test_check_control_enable_ept_violation_checks();
    void test_check_control_enable_pml_checks();

    void test_check_control_vm_exit_control_fields_all();
    void test_check_control_vm_exit_ctls_reserved_properly_set();
    void test_check_control_activate_and_save_preemption_timer_must_be_0();
    void test_check_control_exit_msr_store_address();
    void test_check_control_exit_msr_load_address();

    void test_check_control_vm_entry_control_fields_all();
    void test_check_control_vm_entry_ctls_reserved_properly_set();
    void test_check_control_event_injection_type_vector_checks();
    void test_check_control_event_injection_delivery_ec_checks();
    void test_check_control_event_injection_reserved_bits_checks();
    void test_check_control_event_injection_ec_checks();
    void test_check_control_event_injection_instr_length_checks();
    void test_check_control_entry_msr_load_address();

    void test_check_host_state_all();
    void test_check_host_control_registers_and_msrs_all();
    void test_check_host_cr0_for_unsupported_bits();
    void test_check_host_cr4_for_unsupported_bits();
    void test_check_host_cr3_for_unsupported_bits();
    void test_check_host_ia32_sysenter_esp_canonical_address();
    void test_check_host_ia32_sysenter_eip_canonical_address();
    void test_check_host_verify_load_ia32_perf_global_ctrl();
    void test_check_host_verify_load_ia32_pat();
    void test_check_host_verify_load_ia32_efer();

    void test_check_host_segment_and_descriptor_table_registers_all();
    void test_check_host_es_selector_rpl_ti_equal_zero();
    void test_check_host_cs_selector_rpl_ti_equal_zero();
    void test_check_host_ss_selector_rpl_ti_equal_zero();
    void test_check_host_ds_selector_rpl_ti_equal_zero();
    void test_check_host_fs_selector_rpl_ti_equal_zero();
    void test_check_host_gs_selector_rpl_ti_equal_zero();
    void test_check_host_tr_selector_rpl_ti_equal_zero();
    void test_check_host_cs_not_equal_zero();
    void test_check_host_tr_not_equal_zero();
    void test_check_host_ss_not_equal_zero();
    void test_check_host_fs_canonical_base_address();
    void test_check_host_gs_canonical_base_address();
    void test_check_host_gdtr_canonical_base_address();
    void test_check_host_idtr_canonical_base_address();
    void test_check_host_tr_canonical_base_address();

    void test_check_host_address_space_size_all();
    void test_check_host_if_outside_ia32e_mode();
    void test_check_host_address_space_size_exit_ctl_is_set();
    void test_check_host_address_space_disabled();
    void test_check_host_address_space_enabled();

    void test_check_guest_state_all();
    void test_check_guest_control_registers_debug_registers_and_msrs_all();
    void test_check_guest_cr0_for_unsupported_bits();
    void test_check_guest_cr0_verify_paging_enabled();
    void test_check_guest_cr4_for_unsupported_bits();
    void test_check_guest_load_debug_controls_verify_reserved();
    void test_check_guest_verify_ia_32e_mode_enabled();
    void test_check_guest_verify_ia_32e_mode_disabled();
    void test_check_guest_cr3_for_unsupported_bits();
    void test_check_guest_load_debug_controls_verify_dr7();
    void test_check_guest_ia32_sysenter_esp_canonical_address();
    void test_check_guest_ia32_sysenter_eip_canonical_address();
    void test_check_guest_verify_load_ia32_perf_global_ctrl();
    void test_check_guest_verify_load_ia32_pat();
    void test_check_guest_verify_load_ia32_efer();
    void test_check_guest_verify_load_ia32_bndcfgs();

    void test_check_guest_segment_registers_all();
    void test_check_guest_tr_ti_bit_equals_0();
    void test_check_guest_ldtr_ti_bit_equals_0();
    void test_check_guest_ss_and_cs_rpl_are_the_same();
    void test_check_guest_cs_base_is_shifted();
    void test_check_guest_ss_base_is_shifted();
    void test_check_guest_ds_base_is_shifted();
    void test_check_guest_es_base_is_shifted();
    void test_check_guest_fs_base_is_shifted();
    void test_check_guest_gs_base_is_shifted();
    void test_check_guest_tr_base_is_canonical();
    void test_check_guest_fs_base_is_canonical();
    void test_check_guest_gs_base_is_canonical();
    void test_check_guest_ldtr_base_is_canonical();
    void test_check_guest_cs_base_upper_dword_0();
    void test_check_guest_ss_base_upper_dword_0();
    void test_check_guest_ds_base_upper_dword_0();
    void test_check_guest_es_base_upper_dword_0();
    void test_check_guest_cs_limit();
    void test_check_guest_ss_limit();
    void test_check_guest_ds_limit();
    void test_check_guest_es_limit();
    void test_check_guest_gs_limit();
    void test_check_guest_fs_limit();
    void test_check_guest_v8086_cs_access_rights();
    void test_check_guest_v8086_ss_access_rights();
    void test_check_guest_v8086_ds_access_rights();
    void test_check_guest_v8086_es_access_rights();
    void test_check_guest_v8086_fs_access_rights();
    void test_check_guest_v8086_gs_access_rights();
    void test_check_guest_cs_access_rights_type();
    void test_check_guest_ss_access_rights_type();
    void test_check_guest_ds_access_rights_type();
    void test_check_guest_es_access_rights_type();
    void test_check_guest_fs_access_rights_type();
    void test_check_guest_gs_access_rights_type();
    void test_check_guest_cs_is_not_a_system_descriptor();
    void test_check_guest_ss_is_not_a_system_descriptor();
    void test_check_guest_ds_is_not_a_system_descriptor();
    void test_check_guest_es_is_not_a_system_descriptor();
    void test_check_guest_fs_is_not_a_system_descriptor();
    void test_check_guest_gs_is_not_a_system_descriptor();
    void test_check_guest_cs_type_not_equal_3();
    void test_check_guest_cs_dpl_adheres_to_ss_dpl();
    void test_check_guest_ss_dpl_must_equal_rpl();
    void test_check_guest_ss_dpl_must_equal_zero();
    void test_check_guest_ds_dpl();
    void test_check_guest_es_dpl();
    void test_check_guest_fs_dpl();
    void test_check_guest_gs_dpl();
    void test_check_guest_cs_must_be_present();
    void test_check_guest_ss_must_be_present_if_usable();
    void test_check_guest_ds_must_be_present_if_usable();
    void test_check_guest_es_must_be_present_if_usable();
    void test_check_guest_fs_must_be_present_if_usable();
    void test_check_guest_gs_must_be_present_if_usable();
    void test_check_guest_cs_access_rights_reserved_must_be_0();
    void test_check_guest_ss_access_rights_reserved_must_be_0();
    void test_check_guest_ds_access_rights_reserved_must_be_0();
    void test_check_guest_es_access_rights_reserved_must_be_0();
    void test_check_guest_fs_access_rights_reserved_must_be_0();
    void test_check_guest_gs_access_rights_reserved_must_be_0();
    void test_check_guest_cs_db_must_be_0_if_l_equals_1();
    void test_check_guest_cs_granularity();
    void test_check_guest_ss_granularity();
    void test_check_guest_ds_granularity();
    void test_check_guest_es_granularity();
    void test_check_guest_fs_granularity();
    void test_check_guest_gs_granularity();
    void test_check_guest_cs_access_rights_remaining_reserved_bit_0();
    void test_check_guest_ss_access_rights_remaining_reserved_bit_0();
    void test_check_guest_ds_access_rights_remaining_reserved_bit_0();
    void test_check_guest_es_access_rights_remaining_reserved_bit_0();
    void test_check_guest_fs_access_rights_remaining_reserved_bit_0();
    void test_check_guest_gs_access_rights_remaining_reserved_bit_0();
    void test_check_guest_tr_type_must_be_11();
    void test_check_guest_tr_must_be_a_system_descriptor();
    void test_check_guest_tr_must_be_present();
    void test_check_guest_tr_access_rights_reserved_must_be_0();
    void test_check_guest_tr_granularity();
    void test_check_guest_tr_must_be_usable();
    void test_check_guest_tr_access_rights_remaining_reserved_bit_0();
    void test_check_guest_ldtr_type_must_be_2();
    void test_check_guest_ldtr_must_be_a_system_descriptor();
    void test_check_guest_ldtr_must_be_present();
    void test_check_guest_ldtr_access_rights_reserved_must_be_0();
    void test_check_guest_ldtr_granularity();
    void test_check_guest_ldtr_access_rights_remaining_reserved_bit_0();

    void test_check_guest_descriptor_table_registers_all();
    void test_check_guest_gdtr_base_must_be_canonical();
    void test_check_guest_idtr_base_must_be_canonical();
    void test_check_guest_gdtr_limit_reserved_bits();
    void test_check_guest_idtr_limit_reserved_bits();

    void test_check_guest_rip_and_rflags_all();
    void test_check_guest_rip_upper_bits();
    void test_check_guest_rip_valid_addr();
    void test_check_guest_rflags_reserved_bits();
    void test_check_guest_rflags_vm_bit();
    void test_check_guest_rflag_interrupt_enable();

    void test_check_guest_non_register_state_all();
    void test_check_guest_valid_activity_state();
    void test_check_guest_activity_state_not_hlt_when_dpl_not_0();
    void test_check_guest_must_be_active_if_injecting_blocking_state();
    void test_check_guest_hlt_valid_interrupts();
    void test_check_guest_shutdown_valid_interrupts();
    void test_check_guest_sipi_valid_interrupts();
    void test_check_guest_valid_activity_state_and_smm();
    void test_check_guest_interruptibility_state_reserved();
    void test_check_guest_interruptibility_state_sti_mov_ss();
    void test_check_guest_interruptibility_state_sti();
    void test_check_guest_interruptibility_state_external_interrupt();
    void test_check_guest_interruptibility_state_nmi();
    void test_check_guest_interruptibility_not_in_smm();
    void test_check_guest_interruptibility_entry_to_smm();
    void test_check_guest_interruptibility_state_sti_and_nmi();
    void test_check_guest_interruptibility_state_virtual_nmi();
    void test_check_guest_interruptibility_state_enclave_interrupt();
    void test_check_guest_pending_debug_exceptions_reserved();
    void test_check_guest_pending_debug_exceptions_dbg_ctl();
    void test_check_guest_pending_debug_exceptions_rtm();
    void test_check_guest_vmcs_link_pointer_bits_11_0();
    void test_check_guest_vmcs_link_pointer_valid_addr();
    void test_check_guest_vmcs_link_pointer_first_word();

    void test_check_guest_pdptes_all();
    void test_check_guest_valid_pdpte_with_ept_disabled();
    void test_check_guest_valid_pdpte_with_ept_enabled();

    void test_check_control_reserved_properly_set();
    void test_check_memory_type_reserved();

    void test_debug_dump();
    void test_debug_dump_16bit_control_fields();
    void test_debug_dump_16bit_guest_state_fields();
    void test_debug_dump_16bit_host_state_fields();
    void test_debug_dump_64bit_control_fields();
    void test_debug_dump_64bit_read_only_data_field();
    void test_debug_dump_64bit_guest_state_fields();
    void test_debug_dump_64bit_host_state_fields();
    void test_debug_dump_32bit_control_fields();
    void test_debug_dump_32bit_read_only_data_fields();
    void test_debug_dump_32bit_guest_state_fields();
    void test_debug_dump_32bit_host_state_field();
    void test_debug_dump_natural_width_control_fields();
    void test_debug_dump_natural_width_read_only_data_fields();
    void test_debug_dump_natural_width_guest_state_fields();
    void test_debug_dump_natural_width_host_state_fields();
    void test_debug_dump_vmx_controls();
    void test_debug_dump_pin_based_vm_execution_controls();
    void test_debug_dump_primary_processor_based_vm_execution_controls();
    void test_debug_dump_secondary_processor_based_vm_execution_controls();
    void test_debug_dump_vm_exit_control_fields();
    void test_debug_dump_vm_entry_control_fields();
    void test_debug_dump_vmcs_field();
    void test_debug_dump_vm_control();

    void test_state();
    void test_state_segment_registers();
    void test_state_control_registers();
    void test_state_debug_registers();
    void test_state_rflags();
    void test_state_gdt_base();
    void test_state_idt_base();
    void test_state_gdt_limit();
    void test_state_idt_limit();
    void test_state_segment_registers_limit();
    void test_state_segment_registers_access_rights();
    void test_state_segment_register_base();
    void test_state_msrs();
    void test_state_is_guest();
    void test_state_dump();

    void test_host_vm_state();
    void test_host_vm_state_segment_registers();
    void test_host_vm_state_control_registers();
    void test_host_vm_state_debug_registers();
    void test_host_vm_state_rflags();
    void test_host_vm_state_gdt_base();
    void test_host_vm_state_idt_base();
    void test_host_vm_state_gdt_limit();
    void test_host_vm_state_idt_limit();
    void test_host_vm_state_es_limit();
    void test_host_vm_state_cs_limit();
    void test_host_vm_state_ss_limit();
    void test_host_vm_state_ds_limit();
    void test_host_vm_state_fs_limit();
    void test_host_vm_state_gs_limit();
    void test_host_vm_state_tr_limit();
    void test_host_vm_state_ldtr_limit();
    void test_host_vm_state_es_access_rights();
    void test_host_vm_state_cs_access_rights();
    void test_host_vm_state_ss_access_rights();
    void test_host_vm_state_ds_access_rights();
    void test_host_vm_state_fs_access_rights();
    void test_host_vm_state_gs_access_rights();
    void test_host_vm_state_tr_access_rights();
    void test_host_vm_state_ldtr_access_rights();
    void test_host_vm_state_es_base();
    void test_host_vm_state_cs_base();
    void test_host_vm_state_ss_base();
    void test_host_vm_state_ds_base();
    void test_host_vm_state_fs_base();
    void test_host_vm_state_gs_base();
    void test_host_vm_state_tr_base();
    void test_host_vm_state_ldtr_base();
    void test_host_vm_state_ia32_msrs();
    void test_host_vm_state_dump();

    void test_vmm_state_gdt_not_setup();
    void test_vmm_state();
    void test_vmm_state_segment_registers();
    void test_vmm_state_control_registers();
    void test_vmm_state_rflags();
    void test_vmm_state_gdt_base();
    void test_vmm_state_idt_base();
    void test_vmm_state_gdt_limit();
    void test_vmm_state_idt_limit();
    void test_vmm_state_segment_registers_limit();
    void test_vmm_state_segment_registers_access_rights();
    void test_vmm_state_segment_registers_base();
    void test_vmm_state_ia32_efer_msr();
    void test_vmm_state_dump();
};

#endif
